### ISSUE TITLE
Getting started holograms

### ISSUE THREAD

**Issue by Sylensky** [BentoBoxWorld/AOneBlock#100]
#### Is your feature request related to a problem?

No it is not related to any problem.
#### Describe the solution you'd like us to implement.

Adding holograms next to the magic block upon island creation to introduce the game to the player. Lines like "Break this Block! - Trust me" and maybe configurable lines per broken block would come in handy to give the players a very detailed tutorial during their playtime.
### Additional context

Theres not more to request currently.

**Comment by maxlehot1234** [comment]
+1

It will be a little long to configure, but this thing will help the player during the 1st phase as example. So he will know a big part of the gamemode.

That could be a really nice thing to have. Like each 10 blocks, hologram will appear for like 10 seconds with few informations for the player.


Really nice idea

**Comment by tastybento** [comment]
Hologram support has been added to phases.
