### ISSUE TITLE
SkyBlock Plugin Compatibility

### ISSUE THREAD

**Issue by Disfracus** [BentoBoxWorld/AOneBlock#103]
#### Describe the solution you'd like us to implement.

It would be nice if they added support for SkyBlock plugins, more than anything that when an island type is defined as OneBlock the magic block is created automatically

**Comment by Poslovitch** [comment]
That's not something we can do. Gamemodes are designed to be self-contained, and as such, cannot interact with other plugins, or even gamemodes.
