### ISSUE TITLE
Presitage System

### ISSUE THREAD

**Issue by fredthedoggy** [BentoBoxWorld/AOneBlock#104]
#### Is your feature request related to a problem?

No
#### Describe the solution you'd like us to implement.

I think a presitage system would be a cool part of AOneBlock, so that when you finish the last phase, you don't just restart.

Presitage would be in each phases config file, and you could give a presitage multiplier to each entity/block, and the phase length.
If I said the emerald ore presitage % was 150, then it would become higher every time, or if it was 75, it would become lower
#### Describe alternatives you've considered.

I tried this with a seperate presitage plugin, but it was very hard to hook the plugins together
### Additional context

N/A

**Comment by Poslovitch** [comment]
It sort of is already suggested on BentoBox as an addon: https://github.com/BentoBoxWorld/BentoBox/issues/159

**Comment by fredthedoggy** [comment]
> It sort of is already suggested on BentoBox as an addon: [BentoBoxWorld/BentoBox#159](https://github.com/BentoBoxWorld/BentoBox/issues/159)

I haden't actually seen this, but this is a OneBlock specific presitage, so if it were a addon it would need custom features for each gamemode. I think this would improve the oneblock experience specifically, and there coulx be a skyblock/acidisland version also.

**Comment by fredthedoggy** [comment]
Actually, I was thinking about it and a better way to do this would be make it run commands/assign permissions each time you complete the phases (ex: `lp user %user% permission set AOneblock.maxteamsize.%prestige%`)
This would make it simpler than a full prestige system. You could independently implement Permission/Command Based Multipliers that could be used with the auto-commands to create a prestige system,

**Comment by fredthedoggy** [comment]
I have reworked this idea in #108, so I will close this.
