### ISSUE TITLE
Wait delay between phases!

### ISSUE THREAD

**Issue by Uniquiex** [BentoBoxWorld/AOneBlock#107]
#### Is your feature request related to a problem?

The player can wait for a certain time when he moves to another phase

#### Describe the solution you'd like us to implement.

You can add section to AOneBlock's config.yml wait_delay (second, 0 to disable)
and it can add a hologram above bedrock

**Comment by tastybento** [comment]
Do you mean that this would be an enforced delay? That they would not be able to mine the block until the delay is done?

**Comment by immakita** [comment]
Yes a phase is finished player will wait

**Comment by maxlehot1234** [comment]
+1 for this.

The original map have hologram after each phase, so the player will have to wait 10-30 seconds between phases
The magic block will be a bedrock during this countdown and when the coutdown finish, the magic block will turn back to the new phase starter block.

That could be cool :)

**Comment by tastybento** [comment]
There is now a cooldown feature.
