### ISSUE TITLE
[Request] AOneBlock phase.yml additions

### ISSUE THREAD

**Issue by Fredthedoggy** [BentoBoxWorld/AOneBlock#108]
#### Is your feature request related to a problem?

No.
#### Describe the solution you'd like us to implement.

2 Additions to the phase.yml files:
Currently We Have 4 Sections in phase.yml.
```
'0':
  name: Plains
  firstBlock: GRASS_BLOCK
  biome: PLAINS
  blocks:
    ...
```
My Suggestion is add 2 More Sections.
`Commands: []`
And 
`Requirements: []`

**Comands:**
Commands, would just allow commands to be triggered at the Beginning and End of the phase. They would include the following variables:
```
[Name] (Island Name)
[Owner] (Island Owner)
[User] (Person who broke the block)
[LastPhase]
[NewPhase]
[Blocks]
[Level] (Requires Levels Addon)
[Balance] (Requires Vault)
```

This would allow server devs to create things like:
```
Comands:
  broadcast [Name] Completed [LastPhase] with an island level of [Level]! 
  cobblegenadmin setgen [Owner] [Blocks]
```

**Requirements:**
Requirements would allow people to say "You Need $1000 To Complete this phase"
The Magic Block would turn into bedrock, and every time it is punched, it will check the requirements.  When the requirements are met, the commands will run, and then the next phase will start.

Requirements would have 3 (or more) checks
`Balance` (Vault Balance)
`Permission`
`Level` (Requires Level Addon)

This would slow down people just grinding all the way though, then giving up.

#### Describe alternatives you've considered.

I made this request a few days ago, but I have reworked it since. #104
This would allow for prestige commands/requirements, by just putting them in the Last Phase.
### Additional context

No

**Comment by maxlehot1234** [comment]
+1

**Comment by fredthedoggy** [comment]
A Few Days ago I found a way around this (Its only a partial workaround).

You can use LuckPerms ExtraContexts Papi Feature, Along with Papi Javascript to get true or false, and give permissions that way.
I set it so people have to complete the nether phase to access the nether, and people really enjoyed it.

https://github.com/LuckPerms/ExtraContexts

**Comment by Rothes** [comment]
+1 Very useful feature

**Comment by tastybento** [comment]
Commands should be done but haven't been tested yet. I'll work on this more tomorrow and add in the requirements - these will be done as requirements to _start_ a phase.

```
  # A list of commands can be run at the start and end of a phase. Commands are run as the Console
  # unless the command is prefixed with [SUDO], then the command is run as the player
  # triggering the commands.
  # These placeholders in the command string will be replaced with the appropriate value:
  # [island] - Island name
  # [owner] - Island owner's name
  # [player] - The name of the player who broke the block triggering the commands
  # [phase] - the name of this phase
  # [blocks] - the number of blocks broken
  # [level] - your island level (Requires Levels Addon)
  # [bank-balance] - your island bank balance (Requires Bank Addon)
  # [eco-balance] - player's economy balance (Requires Vault and an economy plugin)
  #
  # Examples:
  # start-commands:
  # - give [player] WOODEN_AXE
  # - broadcast [player] just started OneBlock!
  # end-commands:
  # - [SUDO]summon minecraft:wither
```

**Comment by tastybento** [comment]
Well, I just added them. Tomorrow will be testing then!

**Comment by tastybento** [comment]
```
  # Requirements
  # You can stipulate a set of requirements to start the phase:
  # 
  # economy-balance - the minimum player's economy balance (Requires Vault and an economy plugin)
  # bank-balance - the minimum island bank balance (requires Bank Addon)
  # level - the island level (Requires Levels Addon)
  # permission - a permission string
  #
  # Example:
  # requirements:
  #   bank-balance: 10000
  #   level: 10
  #   permission: ready.for.battle
```

**Comment by fredthedoggy** [comment]
This looks very nice! I was just thinking about how I plan to implement it, and realized that I can't spawn mobs and such if placeholderAPI support is not added for the x/y coordinates. Could you add that, along with a feature to parse for the owner, or the player?

**Comment by BONNe** [comment]
You can use BentoBox placeholders. They are working for all gamemodes.

**Comment by fredthedoggy** [comment]
> You can use BentoBox placeholders. They are working for all gamemodes.

That is my plan, but placeholderAPI support still needs to be added to use bentobox placeholders :)

**Comment by tastybento** [comment]
> This looks very nice! I was just thinking about how I plan to implement it, and realized that I can't spawn mobs and such if placeholderAPI support is not added for the x/y coordinates.

As a workaround, I think you can use [SUDO]summon (name of mob) and it'll spawn where the player is. Please try it and let me know.

> Could you add that, along with a feature to parse for the owner, or the player?

I'll look at it. What do you mean "parse for the owner, or the player" though? What's the output?

**Comment by BONNe** [comment]
tasty, I would recommend just parse any PAPI placeholder.

**Comment by tastybento** [comment]
Okay, done. Let's see how that works.

**Comment by fredthedoggy** [comment]
> > Could you add that, along with a feature to parse for the owner, or the player?
> 
> I'll look at it. What do you mean "parse for the owner, or the player" though? What's the output?

Should have clarified:
A way to parse placeholders as either the owner *or* the player who broke it.

A More advanced version would be parse for the player that broke it if they were part of the island, otherwise parse for the owner.

I'll test this out today though :)
