### ISSUE TITLE
Problem with Block counter

### ISSUE THREAD

**Issue by Skygamer777** [BentoBoxWorld/AOneBlock#109]
#### Describe the bug
Every time i restart my server the oneblock counter resets (using Mariadb)

#### Steps to reproduce the behavior
break 1 or more block

##### Output of `/bbox version` (Mandatory)
Running Paper 1.16.1 Bentobox 1.14.0 Database: JSON (i edited this to mariadb but it didn't worked at all)
```
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by Skygamer777** [comment]
and after you break one or more blocks restart the server and run /ob count

**Comment by tastybento** [comment]
Does the rest of the game work fine, like the islands and everything?

Do `bbox version` in the console and then copy and paste everything it outputs into this ticket so I can see what setup you have.

**Comment by Skygamer777** [comment]
1. No the Island resets but the blocks and animals are still there and i have to break everything in gamemode

2. > bbox version
[06:55:11 INFO]: Running PAPER 1.16.1.
[06:55:11 INFO]: BentoBox version: 1.14.0
[06:55:11 INFO]: Database: JSON
[06:55:11 INFO]: Loaded Game Worlds:
[06:55:11 INFO]: oneblock_world (OneBlock): Overworld
[06:55:11 INFO]: Loaded Addons:
[06:55:11 INFO]: AOneBlock 1.4.0 (ENABLED)
>

**Comment by Skygamer777** [comment]
but yeah the block regenerate animals spawn

**Comment by Skygamer777** [comment]
and the counter works it only resets after reload

**Comment by Skygamer777** [comment]
do you know the problem?

**Comment by Skygamer777** [comment]
i updated the plugin and everything works
