### ISSUE TITLE
[Huge issue] When players do ./ob they got a bedrock block to start their island with default blueprint

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#110]
#### Describe the bug

When players do ./ob they got a bedrock block to start their island with default blueprint

#### Steps to reproduce the behavior

Simply join the server with a dummy account

#### Expected behavior

Should be a grass block, not a bedrock..

##### Output of `/bbox version` (Mandatory)

```
[22:12:37 INFO]: Running PAPER 1.16.1.
[22:12:37 INFO]: BentoBox version: 1.15.0-SNAPSHOT-b1843
[22:12:37 INFO]: Database: JSON
[22:12:37 INFO]: Loaded Game Worlds:
[22:12:37 INFO]: oneblock_world (OneBlock): Overworld
[22:12:37 INFO]: Loaded Addons:
[22:12:37 INFO]: AOneBlock 1.4.1-SNAPSHOT-b123 (ENABLED)
[22:12:37 INFO]: Border 1.0.9 (ENABLED)
[22:12:37 INFO]: ControlPanel 1.13.0-SNAPSHOT-b16 (ENABLED)
```

I just reset my server, so I remove every player data files including the oneblock world and I also remove Databse folder of bentobox and I delete the oneblock_world folder to allow the server to generate a new one.
I also try to delete the blueprints folder and got the same problem.

The only way to fix the issue is to do a ./ob reset 
Its why a lot of players leave the server when they join. No One report this issue to me, but I just realise it :(

Do you know why and do you know how I can fix this?

Thanks again

**Comment by maxlehot1234** [comment]
Nothing on this ? :( @tastybento @Poslovitch Its a really weird issue and it happen to me (OP) too.

**Comment by tastybento** [comment]
I see this issue with Paper Build 99, but I do not see this issue with Paper Build 113. The error is occurring in the the PaperLib asyncTeleport routine. Upgrade to the latest Paper and see if that fixes it.

**Comment by tastybento** [comment]
Confirmed - [this bug](https://github.com/PaperMC/Paper/issues/3934) was fixed in Build 101

**Comment by maxlehot1234** [comment]
Yeah issue fixed when I update PaperMC to build 114 (the new one now :P )

Thanks for the heads-UP. Too many updates per day ahaha.
