### ISSUE TITLE
Digging grass blocks won't fall, but blocks you put will fall

### ISSUE THREAD

**Issue by qq2719035729** [BentoBoxWorld/AOneBlock#111]
About versions of bentobox components：
AoneBlock 1.4.0    Bskyblock-1.14.0  challenges-0.8.3  bentobox-1.14.1
Here is the error displayed by the console digging a block：
[1.txt](https://github.com/BentoBoxWorld/AOneBlock/files/4963600/1.txt)

**Comment by tastybento** [comment]
Please update your server jar - it is an old build with a bug in it.
