### ISSUE TITLE
How to get data from this plugin

### ISSUE THREAD

**Issue by ashwinvin** [BentoBoxWorld/AOneBlock#116]
I would to get stats like number of blocks breaked directly from the AOneBlock plugin but I couldn't find a way to do it. It would a big help if you guys help me find a way. I am kinda new to JAVA. 
Thanks

**Comment by BONNe** [comment]
After migration to the pladdon, it should be possible to get data with other plugins. 
Data is stored in `OneBlockIslands` object.
