### ISSUE TITLE
Placeholder: %aoneblock_my_island_totalcount%

### ISSUE THREAD

**Issue by Rothes** [BentoBoxWorld/AOneBlock#118]
**Description**
to get the island total count, but not the current count

**Placeholder**: `%aoneblock_my_island_totalcount%`

**Comment by RustyDagger** [comment]
I would also very much find this useful.
I was looking for a way to display how many times a player had gone right around all the blocks.

This would let me do some basic math ( total broken % total blocks in phases.) = X and that number could be rounded and displayed quite easy with placeholder api Js.

I considered using the end commands on the last phase the issue with that it only triggers the command on the player that breaks the last block or the island owner it lacks an option to run a command for all the party members.

**Comment by TNTUP** [comment]
This would be useful as some players loves to see how many total blocks they have broken since I started the server or when they started the oneblock for the first time!

Even myself I like statistics :)
