### ISSUE TITLE
Switch phases

### ISSUE THREAD

**Issue by GoldenretriverYT** [BentoBoxWorld/AOneBlock#119]
#### Is your feature request related to a problem?

no

#### Describe the solution you'd like us to implement.

it would be a nice feature to switch between phases you unlocked. (/ob switchphase)

**Comment by Jcodeerd** [comment]
Any updates on this? I really would like that functionality!

**Comment by BONNe** [comment]
This feature is implemented.

The latest dev version even contains GUI that allows choosing phase.
