### ISSUE TITLE
[Question] How to make nether and end world looks much better

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#120]
HI,

I allowed nether and end world, but they looks like this:

Nether:
![image](https://user-images.githubusercontent.com/5159244/92412947-ea90f180-f11b-11ea-9c21-56d20103dfd5.png)

End:
![image](https://user-images.githubusercontent.com/5159244/92412965-fbd9fe00-f11b-11ea-9548-b39332e16e9d.png)

I wondering how I can make these world looks more like nether and end worlds.
Or if you can implement a magic blocks on these world that give only nether blocms (on the nether) and end blocks (on the end world)

Or maybe create default blueprint for nether and end. Right now, I got only the default blueprint and creation is kinda "hard.
Why not allow us to simply import normal schematic for island and than "link them" in blueprint menu?

Thanks for reading and have a nice day

**Comment by maxlehot1234** [comment]
Anything on this "issue" ?

**Comment by InFiniityxSweety** [comment]
How did you get a oneblock world in nether and end mine are completely normal nether and end worlds?

**Comment by maxlehot1234** [comment]
Anything on this?

**Comment by tastybento** [comment]
How did you make these worlds? It is not the default for AOneBlock. The default is that it should be the vanilla nether and no end-island.

**Comment by maxlehot1234** [comment]
I just enable them and create the portals :P

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tastybento** [comment]
Then the Nether was not created properly then. If you stop the server, delete the Nether world and restart it should generate a vanilla nether. The End is not supported in AOneBlock.

**Comment by maxlehot1234** [comment]
Oh ok, I will try and see if it work.

So I am supposed to have a normal nether world instead of the one I have, exact?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tastybento** [comment]
Yes. You should have a normal nether.
