### ISSUE TITLE
Plugins support.

### ISSUE THREAD

**Issue by kFxDaKing** [BentoBoxWorld/AOneBlock#121]
#### Is your feature request related to a problem?

Add support for other plugins like Jobs Reborn, Jets Minions, Quests, Battlepass, etc..
I bought all that plugins and there is problem with all of them and im really sad.

#### Describe the solution you'd like us to implement.

For Jobs Reborn there is problem that it doesnt count blocks from generator.
For jets minions there is problem that, there isnt working Miner minion with generator.
For Quests, again the same you can do quests for mining.
Battlepass same as quests.

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/AOneBlock/issues/88

Creating more cases with the same message will not change outcome.

**Comment by kFxDaKing** [comment]
It was just for Jobs, there is more plugins.

**Comment by BONNe** [comment]
For all "quests" type plugins answer would be the same as in #88. 

About Minions, it could be implemented...

**Comment by tastybento** [comment]
JetsMinions is done.
