### ISSUE TITLE
Ghasts spawn in Nether phase even though they are turned off

### ISSUE THREAD

**Issue by Villmarksjenta** [BentoBoxWorld/AOneBlock#125]
#### Describe the bug
I have turned off ghast spawning in Nether phase so this is in the phases file:
  mobs:
    SKELETON: 50
    MAGMA_CUBE: 100
    GHAST: 0
    PIG_ZOMBIE: 300
    ENDERMAN: 20
    BLAZE: 200
    WITHER_SKELETON: 20
Even though the ghasts are turned to 0, they still spawn. I have even set the region through worldguard to deny ghast spawning.

#### Steps to reproduce the behavior
Not sure what causes it, but its weird that they spawn even though they are set at 0.

#### Expected behavior
No ghast spawning when its set to 0.

##### Output of `/bbox version` (Mandatory)
16.10 15:06:02 [Server] INFO Warps 1.10.0 (ENABLED)
16.10 15:06:02 [Server] INFO Upgrades 0.2.0-SNAPSHOT-b64 (ENABLED)
16.10 15:06:02 [Server] INFO MagicCobblestoneGenerator 2.0.0 (ENABLED)
16.10 15:06:02 [Server] INFO Limits 1.14.0 (ENABLED)
16.10 15:06:02 [Server] INFO Level 2.4.1 (ENABLED)
16.10 15:06:02 [Server] INFO IslandFly 1.8.0 (ENABLED)
16.10 15:06:02 [Server] INFO DimensionalTrees 1.6.0 (ENABLED)
16.10 15:06:02 [Server] INFO ControlPanel 1.7.0 (ENABLED)
16.10 15:06:02 [Server] INFO Challenges 0.8.3 (ENABLED)
16.10 15:06:02 [Server] INFO BSkyBlock 1.14.0 (ENABLED)
16.10 15:06:02 [Server] INFO Biomes 1.13.0 (ENABLED)
16.10 15:06:02 [Server] INFO AOneBlock 1.4.0 (ENABLED)
16.10 15:06:02 [Server] INFO Loaded Addons:
16.10 15:06:02 [Server] INFO oneblock_world (OneBlock): Overworld, Nether*
16.10 15:06:02 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
16.10 15:06:02 [Server] INFO Loaded Game Worlds:
16.10 15:06:02 [Server] INFO Database: JSON
16.10 15:06:02 [Server] INFO BentoBox version: 1.15.0
16.10 15:06:02 [Server] INFO Running PAPER 1.15.2.
```
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
Due to rounding, there is a chance that a Ghast could spawn. If you don't want them to spawn, as a workaround, remove them completely from the config.
