### ISSUE TITLE
On block and phase rollbacks after server crash

### ISSUE THREAD

**Issue by kFxDaKing** [BentoBoxWorld/AOneBlock#129]
#### Describe the bug
On block and phase rollback when server crash. Not only for online players, but for everyone.
My server freezed when i loaded new plugin "LiteBans" via plugin manager, it was not possible to execute "stop", "save-all" nothing, just process kill, so i had to kill process and then i got tons of report, that players onblock and phase rollbacked.

#### Steps to reproduce the behavior
You should have some players in the db and then crash a server somehow? :D 

#### Expected behavior
Should be fixed.

#### Screenshots and videos (Optional)
There isnt any screenshot that can help, ill provide logs and db.

##### Output of `/bbox version` (Mandatory)
```
>....=>.... [13:48:45 INFO]: Běžím na Neplatné (YATOPIA) 1.16.3. (Spigot fork)
>.... [13:48:45 INFO]: Verze BentoBox: 1.15.2-SNAPSHOT-b1896 (Happening on stable version too)
>.... [13:48:45 INFO]: Databáze: MARIADB
>.... [13:48:45 INFO]: Načtené herní světy:
>.... [13:48:45 INFO]: oneblock_world (OneBlock): Svět, Nether*, End*
>.... [13:48:45 INFO]: Načtené doplňky:
>.... [13:48:45 INFO]: AOneBlock 1.4.0 (ENABLED)
>.... [13:48:45 INFO]: Border 2.0.0 (ENABLED)
>.... [13:48:45 INFO]: Chat 1.0.5 (ENABLED)
>.... [13:48:45 INFO]: Level 2.4.1 (ENABLED)
>.... [13:48:45 INFO]: Warps 1.10.0 (ENABLED)
```

#### Plugins (Optional)
```
Plugins (67): AntiAFKPlus, AutoMessage, AutoTool, BentoBox, BlockCommand*, BlockParticles, Citizens, ClearLag, CombatLogX, CommandNPC*, CoreProtect, CrazyAuctions, CrazyCrates, CrazyEnchantments, CrazyEnvoy, DeluxeMenus, DeluxeTags*, DisableJoinMessage*, EasyBackup, EntityDetection, EpicChatPrefix*, EpicSpawners, Essentials, EssentialsGeoIP, EssentialsSpawn, (WorldEdit)FastAsyncWorldEdit, FastLogin, HolographicDisplays, HolographicExtension, HolographicPlaceholders, Item2Chat, ItemFrameTagger*, JetsMinions, JetsSellChests, LiteBans, LoginSecurity*, LuckPerms, MineStore*, Minetrends*, MobFarmManager, Multiverse-Core, NametagEdit*, NoFlyZone, NoPlugins, PlaceholderAPI, Plan, PluginManager*, ProtocolLib, RevoltCrates, SAML, ShopGUIPlus, SkinsRestorer, spark, SuperBoosters, SuperbVote, SuperMobCoins, SuperPouches, TAB, TitleManager, Vault, VillagerLobotomizatorNator, VillagerOptimiser, VoidSpawn, VoidWorld*, VoteParty, Votifier, WorldGuard
```
 
### Additional context (Optional)
Log: https://hastebin.com/pazicipiza.sql
Db before crash: 
[before crash.zip](https://github.com/BentoBoxWorld/BentoBox/files/5494470/before.crash.zip)

Db after crash: 
[after crash.zip](https://github.com/BentoBoxWorld/BentoBox/files/5494469/after.crash.zip)

**Comment by tastybento** [comment]
The only mitigation against crashed - on in this case a killed server is to save the data every so often. The enhancement would be to save the one block island data every so often.

**Comment by dig** [comment]
Auto save enhancement should really be added, it's important to save the data frequently to prevent rollback if the server were to crash.

**Comment by tastybento** [comment]
The latest snapshot now saves the island data:

1. Every 5 broken blocks
2. When a new phase is achieved
3. When a player quits

**Comment by kFxDaKing** [comment]
Thanks for echancement, but i think Every 5 broken blocks is too often, it should lag db i think.

It should be like 50 blocks, its okay if that rollback 50 blocks, that like few minutes, but current rollbacks was in thousands.
