### ISSUE TITLE
[Question] Canm I add new phase and change amount of blocks?

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#13]
HI,

I just want to know if its possible for me to add more phase with more bioms, differents blocks, more blocks per phase, etc?

Thanks again.

**Comment by tastybento** [comment]
Yes. It's possible to change the aoneblocks.yml file in the AOneBlock folder. Read the docs for info: https://bentobox-world.readthedocs.io/en/latest/gamemodes/AOneBlock/#oneblockyml

**Comment by maxlehot1234** [comment]
I mean implement new phase with new biomes so I can have like 20 phase for example.

So the latest one will be on Phase 20 and I will add few more biomes which means few more phases too
