### ISSUE TITLE
Placeholder: Owner, next phase.

### ISSUE THREAD

**Issue by EvilLord1323** [BentoBoxWorld/AOneBlock#134]
Next phase PlaceHolder

**Placeholder**: `%aoneblock_visited_island_nextphase%`
**Placeholder**: `%aoneblock_my_island_nextphase%`

Owner placeholder

**Placeholder**: `%aoneblock_visited_island_owner%`

Protection range

**Placeholder**: `%aoneblock_visited_island_range%`
**Placeholder**: `%aoneblock_my_island_range%`

**Comment by tastybento** [comment]
Next phase is now available. The other placeholders are generic and available: https://docs.bentobox.world/en/latest/BentoBox/Placeholders/
