### ISSUE TITLE
2000% server tick - bentobox (oneblock)

### ISSUE THREAD

**Issue by Maftyyn** [BentoBoxWorld/AOneBlock#136]
#### Describe the bug

So, bentobox(oneblock) is taking 2000% server tick on my server, causes my server to have 800+ ping for all players, i have 8GB RAM and I9-9900k on my server, and around 15-25players on it. 
#### Expected behavior

It should be not that high.
#### Screenshots and videos (Optional)

```
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       0.27%	2,095.75%	 62.87 s	 1,047.87 ms	 0.0	       0.1k	    Task: NewIsland$$Lambda$7020/347860690(Single)
       0.21%	1,675.77%	 48.60 s	   837.88 ms	 0.0	       0.1k	    BlockListener::onNewIsland(IslandCreatedEvent)
       0.15%	 240.53%	 34.28 s	   120.27 ms	 0.0	       0.3k	    Task: IslandGoCommand$$Lambda$6610/169296419(Single)
       0.05%	   0.05%	 11.40 s	     0.02 ms	 3.6	   1,699.6k	    PortalTeleportationListener::onPlayerPortal(PlayerMoveEvent)
       0.03%	   0.40%	  7.96 s	     0.20 ms	 0.1	      39.9k	    BlockListener::onBlockBreak(BlockBreakEvent)
```
##### Output of `/bbox version` (Mandatory)

```
Running on: SPIGOT 1.16.2
Version of bentobox : 1.15.5
Database: JSON
Loaded worlds:
oneblock_world
Loaded addons:
AOneBlock 1.4.6 (ENABLED)
Chat: 1.1.1 (ENABLED)
Likes 2.0.0 (ENABLED)
Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by EvilLord1323** [comment]
What host are you using? Maybe you're hosting overselling?

**Comment by Maftyyn** [comment]
Hicoria.com

**Comment by BONNe** [comment]
Do you have very large island blueprints?

You can adjust island pasting speed in BentoBox config:
https://github.com/BentoBoxWorld/BentoBox/blob/develop/src/main/resources/config.yml#L154

One more option would be to switch to the Paper server version, as it offers some optimizations, that are not in the Spigot version.

It is possible that you will need to adjust the island deletion speed, as it is not optimized for the 1.16.2 version. I would suggest to set it to 1 if you want to islands to be removed after resetting, or 0, if they can stay.

**Comment by tastybento** [comment]
I echo BONNe's question - the lag is coming from NewIsland, which should be instant in OneBlock because there's no blueprint. That's weird. Are you running with stock settings? Could you share more info on your setup?

**Comment by Maftyyn** [comment]
Hey, yeah i was running at stock settings but on Paper which i knew it could do some problems, paper was not working for me because it was pasting error that it couldnt create island so i was going back to spigot instead paper, now i changed it to Yatopia 1.16.4 and everything is looking fine for now, ill text you as there will be more players.
