### ISSUE TITLE
Magic Block Destroyed by water

### ISSUE THREAD

**Issue by Fredthedoggy** [BentoBoxWorld/AOneBlock#137]
#### Describe the bug

When a block that gets destroyed by water (eg. Dried coral) gets touched by water, it breaks even though the magic block should only break due to the player
#### Steps to reproduce the behavior

In the ocean phase specifically, if you leave water there & keep mining, when you get to a dried coral it will be destroyed.

#### Expected behavior

The Magic Block should be immune to water damage

##### Output of `/bbox version` (Mandatory)

Latest versions of everything. (I do not have console access right now for the exact output)

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

N/A

**Comment by EvilLord1323** [comment]
remove a water by bucket or place an any block to place of magic block and enjoy)

**Comment by fredthedoggy** [comment]
> remove a water by bucket or place an any block to place of magic block and enjoy)

I know how to deal with it, the issue is that a lot of players do not. Its just a small qol bug

**Comment by tastybento** [comment]
I must be doing something wrong. I assume dried coral is dead coral? I can kill the coral with a sponge, but I can't get it to wash away...
<img width="843" alt="Screen Shot 2021-03-06 at 6 48 20 PM" src="https://user-images.githubusercontent.com/4407265/110227457-89b95a80-7ead-11eb-83a4-6699e34e412d.png">
Can you give directions?
