### ISSUE TITLE
Placeholder: Other Count, Top10

### ISSUE THREAD

**Issue by YXMAX** [BentoBoxWorld/AOneBlock#139]
Other Count Placeholder

**Placeholder:**  `%aoneblock_[player]_island_count%`

Top10 Placeholder

**Placeholder:**  `%aoneblock_[player]_island_top%`
**Placeholder:**  `%aoneblock_[player]_island_top_name%`

Hopely I Can use on HolographicDisplays plugins

**Comment by tastybento** [comment]
There's another addon called TopBlock that does the top ten now.
