### ISSUE TITLE
[Question] How blueprints works?

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#14]
Hi,

I try to create a blueprint to allow players to start with a 3x3 island to rpvent them to die if they are 4 to join at the same for example.

I try to create a blueprint, but each time, there is only 1 grass block (the default start block)

Can you help me with that please?

Thanks again for your time and for your work on this plugin

**Comment by tastybento** [comment]
Did this not work? https://youtu.be/4gvaG89uxAs

**Comment by maxlehot1234** [comment]
@tastybento I make them to work, but even if I create a 3x3 blocks wide blueprints and use it to create a new island, it become a 3x2 blocks wide island :P

The particles are correctly setup with ./obs bp pos1 and pos2
Anyway its supposed to be a OneBlock thing :) 

Thanks for the yb video, it help me to understand the bp system.
