### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by TheKlimoT** [BentoBoxWorld/AOneBlock#140]
Add new placeholder!

Placeholder how much is left until the next phase on OneBlock Island.

Percentage and scales

Example:

![изображение](https://user-images.githubusercontent.com/26817853/107946673-6c762800-6fa2-11eb-961d-892c2984d5a0.png)
The symbol can be any

**Comment by tastybento** [comment]
This should be done in the SNAPSHOT version, but I cannot test it so easily. Please check it: https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/
See this page for a list of placeholders:
https://docs.bentobox.world/en/latest/gamemodes/AOneBlock/Placeholders/
