### ISSUE TITLE
Default Nether/End Biome

### ISSUE THREAD

**Issue by fredthedoggy** [BentoBoxWorld/AOneBlock#147]
#### Is your feature request related to a problem?

I have nether islands enabled on my server for Nether-based Farms (Piglin, etc), but some players get unlucky and have non-Nether Wastes biomes that cannot spawn piglins.

#### Describe the solution you'd like us to implement.

Implement [BentoBoxWorld/Bskyblock/blob/develop/src/main/resources/config.yml#L93-L95](https://github.com/BentoBoxWorld/Bskyblock/blob/develop/src/main/resources/config.yml#L93-L95) into AOneBlock
and Maybe a biome switcher so that players who already got unlucky can have their islands switched back to nether_wastes?
(eg. when nether chunks load it checks the biome, and sets it to nether_wastes)

#### Describe alternatives you've considered.

Setting up a custom superflat generator.

### Additional context

N/A

**Comment by tastybento** [comment]
To change already generated chunks you'll need to use the Biome addon or something.
