### ISSUE TITLE
[New addon] Per-player block for the begginning

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#15]
#### Is your feature request related to a problem?

Not related to a problem

#### Describe the solution you'd like us to implement.

An addon that will add one more block per player in a team when they spawn for the first time, to prevent collisions to push a player in the void

#### Describe alternatives you've considered.

Create a biggest "island" to start, but I am not able to make the blueprint to work. #14 

### Additional context

N/A

**Comment by tastybento** [comment]
I am looking into adding no-push to the addon so that players don't push each other off the island.

**Comment by Poslovitch** [comment]
> I am looking into adding no-push to the addon so that players don't push each other off the island.

Would be a duplicate https://github.com/BentoBoxWorld/BentoBox/issues/1304.
