### ISSUE TITLE
Water + Lava

### ISSUE THREAD

**Issue by RoyalStevieG** [BentoBoxWorld/AOneBlock#151]
Hi, ive been testing the plugin with some people and it was noted that no-one has found lava. Also the only way to get water has been through villagers. 

Is there a way to add it to the chests? Or make a block of it spawn?

Yeah so that would be great if implemented, couldn't find it anywhere else.

**Comment by tastybento** [comment]
Lava comes later in the game. It's available in the Nether Phase in a chest. You can if you like add a lava bucket to an earlier phase by customizing the chests yml files in the phases folder. However, one of the goals of OneBlock was to be different to skyblock. With SkyBlock you get lava immediately and water too and the game revolves around cobblestone generators. I wanted to avoid that mechanic and as you have literally an unlimited supply of blocks from the magic block, that should be your source of material!

For water, you can wait for the ocean phase, or build a cauldron and wait for it to rain. Or you could give them a water bucket if you like, but that would be too easy!

**Comment by RoyalStevieG** [comment]
Ah ok, I see. Yeah that all makes sense. Spreading it out and not being reliant on a cobble generator is awesome. 
Thanks for the feedback!
Yeah we got our water buckets by trading with wandering traders.
Thanks again for the awesome response
