### ISSUE TITLE
Chest break TP

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/AOneBlock#154]
#### Describe the bug
When we break a chest just under the player we are tp on the void instantly

#### Steps to reproduce the behavior
Just break a chest

#### Screenshots and videos (Optional)
https://www.youtube.com/watch?v=gy107TnWNvQ

##### Output of `/bbox version` (Mandatory)
```
Serveur Invalide (YATOPIA) 1.16.5.
 Version de BentoBox : 1.16.0-SNAPSHOT-b1998
 Base de données : JSON
 Mondes de jeu chargés :
 boxed_world (Boxed) : Overworld, Nether*, End*
 oneblock_world (OneBlock) : Overworld, Nether*
 Addons chargés :
 AOneBlock 1.5.2 (ENABLED)
 Bank 1.3.0 (ENABLED)
 Biomes 1.14.1-SNAPSHOT-b200 (ENABLED)
 Border 2.1.0-SNAPSHOT-b81 (ENABLED)
 Boxed 1.0.0 (ENABLED)
 Chat 1.1.2 (ENABLED)
 Level 2.6.0 (ENABLED)
 Likes 2.1.1-SNAPSHOT-b43 (ENABLED)
 Limits 1.15.5 (ENABLED)
 Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (49): AdvancedAchievements, AntiCooldown, BentoBox, BlockLocker, BottledExp, ChatBrawl, Citizens, CitizensBooks, CitizensCMD, CMI, CMILib, CMIPaperLib, CommandBlocker, CrazyCrates, CubCustomDrops, CustomCrafting, EntityDetection, EntityTrackerFixer, FeatherBoard*, HeadDatabase, IllegalStack, JetsMinions, Jobs, LuckPerms, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, PlaceholderAPI, ProCosmetics, ProtocolLib, Quests, QuestsGUI, RegisterCommands, ShopGUIPlus, spark, TrMenu, UltimateTimber, Vault, WeatherPlugin, WildStacker, WildTools, WolfyUtilities, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3
```

**Comment by fredthedoggy** [comment]
Please reproduce this on a server with 0 other plugins.
This looks like an anticheat's doing, but I do not fully know.
(I don't notice an anticheat in your plugins list, but there may be one)

**Comment by tastybento** [comment]
When you break a chest (or any block < 1 block high, like slab, carpet, etc.), AOneBlock will teleport you up a bit so you will not fall if you are on top of the block. If you are teleported into the void, I expect it is another plugin, like @fredthedoggy says. Check your plugins.
