### ISSUE TITLE
Its a request

### ISSUE THREAD

**Issue by srrawr11** [BentoBoxWorld/AOneBlock#160]
Hi, I would like to request if its possible to add any permission that gives fly in the island.
For example if you are outside of your island region, the fly won't be working.

Thanks!

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/IslandFly

**Comment by srrawr11** [comment]
Thanks to reply me :)
I have a question, there is any permission? Coz for example I would like to put it in come ranks..

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/IslandFly#permissions

**Comment by srrawr11** [comment]
Muchas gracias por tu atencion! :)
