### ISSUE TITLE
Progress Placeholders

### ISSUE THREAD

**Issue by MrSwalbert** [BentoBoxWorld/AOneBlock#163]
#### Describe the bug
There is a placeholder called `%aoneblock_my_island_percent_done%` that displays `phase completion percentage`. I have completed `18%` of the current phase, but the placeholder displays `82%`. The placeholder `%aoneblock_my_island_done_scale%` seems to count down as well. 

#### Steps to reproduce the behavior
N/A

#### Expected behavior
I think it would make more sense to have this count up to 100%, not down to 0% like it currently is - hence why I think this is unintentional.

##### Output of `/bbox version` (Mandatory)

```
[20:07:43 INFO]: Running Invalid (AIRPLANE) 1.16.5.
[20:07:43 INFO]: BentoBox version: 1.16.1
[20:07:43 INFO]: Database: JSON
[20:07:43 INFO]: Loaded Game Worlds:
[20:07:43 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[20:07:43 INFO]: Loaded Addons:
[20:07:43 INFO]: AOneBlock 1.5.4 (ENABLED)
[20:07:43 INFO]: Border 3.1.0 (DISABLED)
[20:07:43 INFO]: Level 2.6.3 (ENABLED)
```
 
### Additional context (Optional)
If this is intentional, I would personally consider changing it or adding another placeholder.

**Comment by tastybento** [comment]
Hmm. Yes, I agree. It is supposed to show how much you have done, not how much you still have to do.

**Comment by tastybento** [comment]
Please try the latest build from ci.bentobox.world and let me know if that works for you.

**Comment by MrSwalbert** [comment]
That's a lot better. Thanks for your speedy fix.
