### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by srrawr11** [BentoBoxWorld/AOneBlock#164]
Version: Paper 1.65.5
Edicion: Java 1.8
Gamemode: AOneBlock

When I activated the flag in the config.yml and I tried to jump to the void it started spams this and I ain't died..
Link: https://pastebin.com/qQGcY90a

I have reported the error like 1 month ago and no onw answered me o attended.
https://github.com/BentoBoxWorld/VoidPortals/issues/10

**Comment by tastybento** [comment]
Let's discuss on VoidPortals.
