### ISSUE TITLE
Null Placeholder

### ISSUE THREAD

**Issue by MrSwalbert** [BentoBoxWorld/AOneBlock#165]
#### Is your feature request related to a problem?
When a player does not have a OneBlock island, the core placeholders return as `null`. This is causing our island panel not to open/function and throw errors.

#### Describe the solution you'd like us to implement.
Can they maybe return a default value like `N/A` or `None`?

### Additional context
For example, the placeholder in the "levels" addon returns `0` when a user does not have an island.

**Comment by fredthedoggy** [comment]
Which placeholder to be exact? On my scoreboard for example it just shows a blank message when there is no value.
Also, could you paste a log file here so I can see exactly where the error stems from

**Comment by tastybento** [comment]
All of the placeholders _should_ return "" if the player doesn't have an island. Like Fred said, share the name of the placeholder. Also do `/bbox version` and copy the text shown here so I know what versions of everything you are running.
