### ISSUE TITLE
How weight system works?

### ISSUE THREAD

**Issue by OguzhanUmutlu** [BentoBoxWorld/AOneBlock#170]
I am going to make it in Bedrock Edition and i need weights of all blocks and entities. In your yaml files there are DIRT: 1000 etc. lines, what is 1000 meaning?

**Comment by OguzhanUmutlu** [comment]
Is it like 1000/all values ?

**Comment by Fredthedoggy** [comment]
It is out of the total amount, so if there is a total of 500, then a weight of 5 would be 1/100th

**Comment by OguzhanUmutlu** [comment]
Thanks!
