### ISSUE TITLE
Remove inventory when i restart my island

### ISSUE THREAD

**Issue by jarruego** [BentoBoxWorld/AOneBlock#173]
#### Describe the bug

island reset dont erase my previous inventory. Any solution? I put keep-previous-island-on-reset: false in config.yml
#### Steps to reproduce the behavior

Put keep-previous-island-on-reset: false in config.yml and restart server
#### Expected behavior

Remove inventory when i restart the island
##### Output of `/bbox version` (Mandatory)

```
_______
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

I use SepareWorldItems plugin. I don't know if it affects

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/AOneBlock/blob/develop/src/main/resources/config.yml#L268-L323

**Comment by jarruego** [comment]
Sorry, wrong place. Was for BSkyBlock
