### ISSUE TITLE
Bad block material in Plains: GRASS_PATH

### ISSUE THREAD

**Issue by EchoRapidz** [BentoBoxWorld/AOneBlock#176]
**Issue:**
AOneblock errors on a clean installation

**Reproduce:**
1. Create a Paper server on 1.17
2. Download Bentobox 1.17
3. Add the Aoneblockaddon
4. Start the server

**Expected behavior**
For there to be no error

**Log:**

https://pastebin.com/JD9cz3QM

**Temp Fix:**

1. Remove  "GRASS_PATH: 100" from home/plugins/BentoBox/addons/AOneBlock/phases/0_plains.yml
2. Remove "GRASS_PATH: 1" from  home/plugins/BentoBox/addons/AOneBlock/phases/8500_plenty.yml

**Versions:**

Server: git-Paper-63 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 1d194e5)

[14:50:18 INFO]: Running PAPER 1.17.
[14:50:18 INFO]: BentoBox version: 1.17.0
[14:50:18 INFO]: Database: JSON
[14:50:18 INFO]: Loaded Game Worlds:
[14:50:18 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[14:50:18 INFO]: Loaded Addons:
[14:50:18 INFO]: AOneBlock 1.7.0 (ENABLED)

**Plugin List**
Plugins (1): BentoBox

**Comment by BONNe** [comment]
In minecraft 1.17 mojang changed GRASS_PATH to the DIRT_PATH.

You need to update phases with new blocks/mobs, or remove your local ones and let AOneBlock to regenerate them.

I understand wanting an astounding, but currently, there is not one.

**Comment by EchoRapidz** [comment]
This is on a clean installation - it generates the wrong value on 1.17

**Comment by BONNe** [comment]
AOneBlock 1.7.0 is not the latest version. It is for 1.16.5.

If you want the latest, you need to use AOneBlock version form the dev server:
https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/

**Comment by EchoRapidz** [comment]
Ah i see, thank you

**Comment by tastybento** [comment]
> @tastybento You did not increase the version after the last release and dev versions are still on 1.7 :D

Gotcha. I'm releasing 1.8.0 now.
