### ISSUE TITLE
new blocks 1.17

### ISSUE THREAD

**Issue by yogi7777** [BentoBoxWorld/AOneBlock#185]
Hi, 

can I add the new blocks in your phases config? aka copper_ore, block of amethyst and and and?

thanks for your info :)

**Comment by tastybento** [comment]
Yes, you can definitely! You can find the name of the material here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

If you come up with a good set and want to contribute it back, please feel free to do so.
