### ISSUE TITLE
Can´t build snowman or irongolem

### ISSUE THREAD

**Issue by Minecrafter702** [BentoBoxWorld/AOneBlock#187]
### Expected behavior

Players needs to build an Irongolem for a challenge, but they arent able´to build one. 

### Observed/Actual behavior

![2021-08-01_09 44 25](https://user-images.githubusercontent.com/88267024/127763399-7425e570-7681-414e-89aa-af58bdf1369d.png)

### Steps/models to reproduce

Build a Irongolem with 4 iron blocks and a carved pumpkin.

### BentoBox version

![2021-08-01_09 45 18](https://user-images.githubusercontent.com/88267024/127763496-3f6711dc-34b3-4a36-9937-f856da1c7625.png)

### Plugin list

![2021-08-01_09 46 14](https://user-images.githubusercontent.com/88267024/127763513-dc5f7d71-c52b-41fd-87a9-bc32622273d6.png)

**Comment by tastybento** [comment]
You have the Limits add-on. Maybe the golems are limited in it? Try removing the Limits addon and see what happens.
