### ISSUE TITLE
Per Player Locales

### ISSUE THREAD

**Issue by 0xBit-MC** [BentoBoxWorld/AOneBlock#190]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

This feature would get the clients locale language type and automatically register the user with their language. This makes it easier for server administrators to make servers that are multi-lingual and support many different variations of users across the globe.

You already have locales in `plugins/BentoBox/locales/BentoBox` as well as `plugins/BentoBox/locales/<addon>`. This is already setup to work, you'd just need to replace all command text outputs to reference the players saved locale.

### Describe alternatives you've considered.

Reference a completed exampled in Towny at: https://github.com/TownyAdvanced/Towny/issues/4926

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
Not sure how does it relates to the Towny plugin... but sure... you already can do that.
Players just need to run:
`/[player_cmd] language` command and change it to the preferred lang.

**Comment by tastybento** [comment]
@0xBit-MC How is this different to what BONNe wrote? Players can set their language in the UI.
