### ISSUE TITLE
[New Feature] Implement block break PER game placeholder

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#20]
#### Describe the solution you'd like us to implement.

Add a new placeholder that allow us to see the amount of block break by me and my team (NOT all players). Can be useful to put int he TAB or the scoreboard.
Something like this: %[gamemode]_island_blocksbreak_count% 

If we are 4 in the island, we need to know all blocks break for all players in the team.

If we start a new game, reset block break to 0.

Thanks again if its something possible to do

**Comment by tastybento** [comment]
Is this provided already?
https://bentobox-world.readthedocs.io/en/latest/gamemodes/AOneBlock/Placeholders/

**Comment by maxlehot1234** [comment]
@tastybento Yeah but how I can know the block break by player B and by player C for example?

**Comment by tastybento** [comment]
The block break count is per island, so you can only get either the count for the island you are on, for example, if you are a visitor, or from your own island. That's all that's available.

**Comment by maxlehot1234** [comment]
Yeah, but is it possible to implement it in the TAB ? Or implement a placeholder wiuth player1, player2, player3, player4 in it?

This can be cool to have to know which member break block and which one do nothing :P as example

**Comment by tastybento** [comment]
The current placeholders can be put in TAB but are just per island. There's no per-player tracking and I don't want to get into that tracking and management, sorry, but it's a no from me.

**Comment by maxlehot1234** [comment]
But can another dev (maybe mine) can develop an addon or its impossible with actual API?

**Comment by tastybento** [comment]
In theory, anything is possible, but this would be messy. Your dev might find a way.

**Comment by maxlehot1234** [comment]
> In theory, anything is possible, but this would be messy. Your dev might find a way.

Im pretty sure he will :)

Thanks again
