### ISSUE TITLE
Elytras

### ISSUE THREAD

**Issue by srrawr11** [BentoBoxWorld/AOneBlock#200]
### Is your feature request related to a problem?

Using elytras in the island and can go to others island.
Might be you already put it but I didn't find it, sorry.

### Describe the solution you'd like.

I do not know if its possible to block them as /ob fly.. like If you get out from your island border it deactivated suddenly.

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

.

**Comment by tastybento** [comment]
If you want to disable Elytra there is an island setting to do that. Do you want to stop their use, or just make it so you can't go to another island? You could use border to stop exiting the island space.

**Comment by srrawr11** [comment]
I just want to make it so they can't go to another island.

**Comment by tastybento** [comment]
Okay, I recommend using the Border addon.
