### ISSUE TITLE
Ability to edit the Percentage scale placeholder or change it to a more readable 

### ISSUE THREAD

**Issue by amarcais53** [BentoBoxWorld/AOneBlock#207]
### Is your feature request related to a problem?

Im trying use a placeholder called %aoneblock_my_island_done_scale% but its litteraly unreadable

### Describe the solution you'd like.

it would be better replacing the actual symbol by a more bigger and readable like that ■ or that ●
i made 2 exemple here 
https://imgur.com/YjAuxLR
https://imgur.com/BQnSlVd
![old](https://user-images.githubusercontent.com/62488520/136693977-cfa310af-48b6-4abb-8869-86994b6d5111.png)
![new](https://user-images.githubusercontent.com/62488520/136693979-3d63928b-6f94-4f92-abcf-56f01c840e0e.png)

### Describe alternatives you've considered.

Maybe add a way trough the lang files to edit the placeholder 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Okay, this is done. There's a new settings in config.yml:

```
    # Placeholder customization
    # Symbol for the percentage completed scale bar
    placeholders:
      scale-symbol: "■"
```

You can put what you like in there now, or even more than 1 character if you like.

The snapshot is available on https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/
