### ISSUE TITLE
ends-commands not workin in phase.yml

### ISSUE THREAD

**Issue by iSeitan** [BentoBoxWorld/AOneBlock#215]
### Expected behavior

with ends-command, at the end of a phases it would execute a command

### Observed/Actual behavior

it throw an error and dont execute the commands

### Steps/models to reproduce

using this phase file https://pastebin.com/kUiV5d2E
finishing the phase throw this error https://pastebin.com/v5b22spN

### BentoBox version

[18:25:22 INFO]: Serveur PURPUR 1.17.1.
[18:25:22 INFO]: Version de BentoBox : 1.18.1-SNAPSHOT-b2182
[18:25:22 INFO]: Base de données : JSON
[18:25:22 INFO]: Mondes de jeu chargés :
[18:25:22 INFO]: oneblock_world (OneBlock) : Overworld
[18:25:22 INFO]: Addons chargés :
[18:25:22 INFO]: AOneBlock 1.9.0-SNAPSHOT-b238 (ENABLED)
[18:25:22 INFO]: Bank 1.4.0-SNAPSHOT-b52 (ENABLED)
[18:25:22 INFO]: Border 3.3.0-SNAPSHOT-b127 (ENABLED)
[18:25:22 INFO]: Level 2.8.0-SNAPSHOT-b480 (ENABLED)
[18:25:22 INFO]: TwerkingForTrees 1.4.3 (ENABLED)
[18:25:22 INFO]: Upgrades 0.2.0-SNAPSHOT-b84 (ENABLED)
[18:25:22 INFO]: Warps 1.11.2-SNAPSHOT-b311 (ENABLED)

### Plugin list

 Actionbar, ActionHealth, AdvancedChests, Aurora, AutoMessage, BattlePass, BentoBox, BestTools, BetterTridents, BuildersWand, BungeeGuard, BuycraftX, ChatBrawl, ChatInjector, ChestSort, Chunky, Citizens, CoreProtect, DeathPenalties, DeluxeMenus, DeluxeSellwands, DiscordSRV, eco, EcoEnchants, EcoItems, EcoSkills, EpicCraftingsPlus, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FeatherBoard, GCore, GHolo, GoldenCrates, GSit, HackedCore*, HackedServer*, HeadDatabase, HolographicDisplays, HoloMobHealth, InfiniteVouchers, Insights, InteractionVisualizer, InteractiveChat, InventoryRollbackPlus, InvUnload, JetsMinions, LagAssist, LuckPerms, MineableSpawners, MMOBars, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, MyCommand, MythicLib, MythicMobs, NexEngine, Obsidiantolava, OpenInv, PinPrompt, PL-Hide-Pro, PlaceholderAPI, Plan, PlayerProfiles, Playtimes*, ProJumpPads*, ProtocolLib, QSFindItemAddOn, QuickShop, Reforges, RHLeafDecay, SafeDrop*, ShopGUIPlus, ShopGUIPlus-SellGUI, ShopGUIPlusMineableSpawnersBridge, Shopkeepers, spark, SSX-Connector*, StreamingDrops, TAB, TempFly, TimeIsMoney, TradeSystem, TutorialCreator, UltimateCore, UltimateCore-Farm, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, VoidSpawn, Votifier, VotingPlugin, WorldBorderAPI, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3

**Comment by tastybento** [comment]
This is fixed in V1.4.0 release of Bank: https://github.com/BentoBoxWorld/Bank/releases/tag/1.4.0
