### ISSUE TITLE
Duping items with central chest

### ISSUE THREAD

**Issue by Krin37** [BentoBoxWorld/AOneBlock#217]
### Expected behavior

A user puts items inside a chest that appears on any phase, but when he mines it,  the items inside won't dupe

### Observed/Actual behavior

A user puts some items inside any chest that appears on any phase, and when he mines the chest, the items inside that were not set in the chest file are duped.

Here is a video showing the dupe:
https://medal.tv/es/games/imported-clips/clips/4ZNaNWudlKVR_/dzFwinjl7CCm?invite=cr-MSxncHUsMjA4MDU3MTks

### Steps/models to reproduce

Mine the central block untill you get a chest
Pick any item you want to dupe
Put it inside the chest
Mine the chest
Items duped

### BentoBox version

[10:37:55 INFO]: Iniciando AIRPLANE 1.16.5.
[10:37:55 INFO]: BentoBox versión: 1.16.5
[10:37:55 INFO]: Base de datos: MARIADB
[10:37:55 INFO]: Cargados los mundos del juego:
[10:37:55 INFO]: oneblock_world (OneBlock): Overworld
[10:37:55 INFO]: Complementos cargados:
[10:37:55 INFO]: AOneBlock 1.9.0-SNAPSHOT-b227 (ENABLED)
[10:37:55 INFO]: Border 3.0.1 (ENABLED)
[10:37:55 INFO]: Chat 1.1.4 (ENABLED)
[10:37:55 INFO]: Level 2.8.0-SNAPSHOT-b480 (ENABLED)
[10:37:55 INFO]: TwerkingForTrees 1.4.3 (ENABLED)

### Plugin list

Plugins (86): 40ServidoresMC, AdvancedEnchantments, AdvancedPortals, AlonsoTags, ArmorStandTools, asCMD*, AureliumSkills, bAnnouncer*, BattlePass, BCommons*, BeastTokens, BeautyQuests, BentoBox, BestTools, BuycraftX, ChangeSlots, CheckFlyCommand, Citizens, CMILib, CoreProtect, CubCustomDrops, CustomOreGen, DeathMessages, DeluxeMentions, DeluxeMenus, DeluxeSellwands, Elevator, Essentials, EssentialsSpawn, EvenMoreFish, ExecutableItems, EzChat*, GadgetsMenu, GoldenCrates, GSigns, GSit, HandyOrbs, HeadDatabase, HolographicDisplays, InventoryRollbackPlus, InvisibleItemFrames, JetsMinions, JetsPrisonMines, Jobs, JPremium*, LeaderHeadsRevamped, LuckPerms, Marriage, MineableSpawners, MobFarmManager, Multiverse-Core, MythicMobs, NBTAPI, NexEngine, OreRegenerator, PL-Hide, PlaceholderAPI, PlayerWarps, ProtocolLib, PvPManager, QuickShop, Rankup, RoyaleEconomy, SCore, ShopGUIPlus, Shopkeepers, SkinsRestorer, spark, StatiscticCounter*, TAB, TabCompleteFilter, TimedRewards*, UltimateAutoRestart, UpgradeableHoppers, Vault, ViaVersion, VoidChest, VoidGen, VoidSpawn, VoteParty, Votifier, WorldBorderAPI, WorldEdit, WorldGuard, zAuctionHouseV3, zKoth

**Comment by Jcodeerd** [comment]
I can't seem to reproduce it, tried it a few times

**Comment by Krin37** [comment]
I could reproduce it always even when using only the BentoBox plugin, here is a screenshot of duped swords 
![image](https://user-images.githubusercontent.com/83928076/144422605-4e9e5050-cdc5-4d76-ac5e-b52ba7758b3d.png)

**Comment by Krin37** [comment]
Updated BentoBox but nothing changed

Iniciando AIRPLANE 1.16.5.
[13:38:32 INFO]: BentoBox versión: 1.16.6
[13:38:32 INFO]: Base de datos: MARIADB
[13:38:32 INFO]: Cargados los mundos del juego:
[13:38:32 INFO]: oneblock_world (OneBlock): Overworld
[13:38:32 INFO]: Complementos cargados:
[13:38:32 INFO]: AOneBlock 1.9.0-SNAPSHOT-b227 (ENABLED)
[13:38:32 INFO]: Border 3.0.1 (ENABLED)
[13:38:32 INFO]: Chat 1.1.4 (ENABLED)
[13:38:32 INFO]: Level 2.8.0-SNAPSHOT-b480 (ENABLED)
[13:38:32 INFO]: TwerkingForTrees 1.4.3 (ENABLED)

**Comment by BONNe** [comment]
Do you use the latest AirPlane?

I know that there was a spigot duplication bug a while ago... like 2-3 months ago.
Spigot has fixed it and I know that the issue is fixed in Paper too.

As I am not AirPlane user, I do not know if they has fixed it.

**Comment by Krin37** [comment]
Yes I do use the last Airplane version, also checked that to be sure it was not due to not updated, but is not the case
[13:49:36 INFO]: This server is running Airplane version git-Airplane-12 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Airplane-"0789789" (MC: 1.16.5)

**Comment by Krin37** [comment]
Tested with paper 1.16.5-790 (last build) and it happened again

**Comment by Krin37** [comment]
Thank  you for your quick response :d

**Comment by Krin37** [comment]
No worries, our dev team fixed it. 👯

**Comment by BONNe** [comment]
You need to understand that this is free plugin and developers are doing it in their free time.

If you want a premium support with instant bug fixes, you should search for premium plugin or hire a developer that will work on your plugins.

If you get upset that there are no response then sorry, but people has their main work and life to do.

**Comment by Krin37** [comment]
If I'm upset is because you responded super fast to say it was only my fault, but not to do further investigations or to just say received and noted.
