### ISSUE TITLE
[Bug] Phase title spawn sometimes when I join the island for less than 1 second.

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#22]
#### Describe the bug

Some time, when I join my "island" I see the Phase title for like 1 sec.
It pop and disappear really fast, buts its quite weird to have it spawn sometime when I join the island 

#### Steps to reproduce the behavior

I run the default setup, so I have no idea.

#### Expected behavior

This title should pop when a new Phase start, not supposed to pop when I join the island.

##### BentoBox Version (Mandatory)

```
[17:14:32 INFO]: Running PAPER 1.15.2.
[17:14:32 INFO]: BentoBox version: 1.12.0
[17:14:32 INFO]: Database: JSON
[17:14:32 INFO]: Loaded Game Worlds:
[17:14:32 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[17:14:32 INFO]: Loaded Addons:
[17:14:32 INFO]: AOneBlock 1.1.5 (ENABLED)
[17:14:32 INFO]: Border 1.0.7 (ENABLED)
[17:14:32 INFO]: Challenges 0.8.1 (ENABLED)
[17:14:32 INFO]: Chat 1.0.5 (ENABLED)
[17:14:32 INFO]: Level 1.9.3 (ENABLED)
[17:14:32 INFO]: Limits 1.9.4 (ENABLED)
[17:14:32 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (22): AsyncWorldEdit, AutoPickup, BentoBox, CMI, DeluxeChat, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, PlaceholderAPI, ProtocolLib, SkinsRestorer, UltraCustomizer, Vault, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard
```
 
If it change anything I run java 8
And the server was host on my windows 10 PC with 16GB dedicated to the server. (Its a localhost server to test everything before run it on a production server)

Thanks again for your help.

**Comment by tastybento** [comment]
This isn't coming from the server. It sounds like a client bug. Are you using the vanilla client? The phase name is only shown when a block is broken. There is no link to teleporting. It might be a figment of the world being cached for some reason. When you say "join your island" are you teleporting in from another world?

**Comment by maxlehot1234** [comment]
> This isn't coming from the server. It sounds like a client bug. Are you using the vanilla client? The phase name is only shown when a block is broken. There is no link to teleporting. It might be a figment of the world being cached for some reason. When you say "join your island" are you teleporting in from another world?

Yeah, by default I join the Spawn "world"
I do ./ob to be teleported on the oneblock world on my "island"
Sometimes when I break a block, I see the Phase name title for less than 1 second.

**Comment by tastybento** [comment]
So, just to clarify, you see the title when you break the block then?

**Comment by maxlehot1234** [comment]
Yeah.
When I rejoin the island, I saw the phase title again. 
If I put 2 hours on the same Phase and than logout and login again, I can see the phase title after breaking a block again, but not all the time.

Not sure that its a client side issue.

**Comment by tastybento** [comment]
If in the other bug you were killing the server without letting files save, then this could be a reason too.
