### ISSUE TITLE
Bug, Duplication with Chest

### ISSUE THREAD

**Issue by Teykingo** [BentoBoxWorld/AOneBlock#220]
### Expected behavior

I wouldn't think there would be duplication in the chest

### Observed/Actual behavior

when you destroy a chest one of the items in the chest is duplicated
look,
in the chest there is a tree. When I break the trunk, it gives me 1 more tree, so 2 trees!

https://user-images.githubusercontent.com/96445458/146827050-2fe6e579-7fb7-49af-8f74-9fc76bdac4f7.mp4

.

### Steps/models to reproduce

Break the trunk (from the oneblock)

### BentoBox version

![image](https://user-images.githubusercontent.com/96445458/146827232-dd7277b2-4c97-4407-95f3-fab91a24d311.png)

### Plugin list

![image](https://user-images.githubusercontent.com/96445458/146827287-12fed183-2651-49fe-8a5d-2af48828cd25.png)

**Comment by tastybento** [comment]
Does it happen if you change drop-on-top to false in config.yml, like this:

```
island:
  # Drop broken blocks on top of magic block
  # If you want Jobs or other plugins to recognize magic block breaking this must be false
  # Added since 1.3.0.
  drop-on-top: false
```

**Comment by Teykingo** [comment]
> Cela se produit-il si vous remplacez drop-on-top par false dans config.yml, comme ceci :
> 
> ```
> island:
>   # Drop broken blocks on top of magic block
>   # If you want Jobs or other plugins to recognize magic block breaking this must be false
>   # Added since 1.3.0.
>   drop-on-top: false
> ```

![image](https://user-images.githubusercontent.com/96445458/146907794-ff2389a8-a94c-4df4-b44d-97e41bb8e379.png)
it's on True

**Comment by Fredthedoggy** [comment]
Try changing it to false, and attempt the glitch again
