### ISSUE TITLE
[Bug] Islands not save automatically. Data loss in case of server shutdown.

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#23]
#### Describe the bug

I start an island, work on it for like 15 minutes and I shutdown the server.
The thing is the work done in the last 10 minutes was not save, so I need to start again where I am on the last save.
Is it possible to do something to save everything more often? Like 1 minute, 2 minutes?
Imagine in case of a server shutdown for any reason and players will lost their last 15 mintues of work and their 15 minutes hard-grinding. Especially if they found something really unique in a chest and they lost it because the island was not save... That will be really, really sad.

#### Steps to reproduce the behavior

N/A

#### Expected behavior

An auto-save of the island each 1-2 minutes will be perfect and allow everyone to build and build and grind without any issues. In case of a server shutdown they will lost 1-2 minutes of works (really sad, but much better than 10-15 minutes)

##### BentoBox Version (Mandatory)

```
[17:14:32 INFO]: Running PAPER 1.15.2.
[17:14:32 INFO]: BentoBox version: 1.12.0
[17:14:32 INFO]: Database: JSON
[17:14:32 INFO]: Loaded Game Worlds:
[17:14:32 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[17:14:32 INFO]: Loaded Addons:
[17:14:32 INFO]: AOneBlock 1.1.5 (ENABLED)
[17:14:32 INFO]: Border 1.0.7 (ENABLED)
[17:14:32 INFO]: Challenges 0.8.1 (ENABLED)
[17:14:32 INFO]: Chat 1.0.5 (ENABLED)
[17:14:32 INFO]: Level 1.9.3 (ENABLED)
[17:14:32 INFO]: Limits 1.9.4 (ENABLED)
[17:14:32 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (22): AsyncWorldEdit, AutoPickup, BentoBox, CMI, DeluxeChat, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, PlaceholderAPI, ProtocolLib, SkinsRestorer, UltraCustomizer, Vault, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard
```
 
I realize that yesterday when testing, but no time to create a ticket before.

Thanks again

**Comment by tastybento** [comment]
What, what is not saving? This shouldn't happen at all. If you shutdown your server properly everything should be saved. I don't know what you mean by not saved though. Do you mean the world and blocks and stuff? Even that should be saved properly when you shutdown.

**Comment by maxlehot1234** [comment]
Yeah I mean, blocks, blocks place, blocks break, inventory, etc.

If server shutdown, everything get lost.

If I logout and login its fine. It only happen if the server shutdown instantly

**Comment by tastybento** [comment]
It sounds like the server is not being shutdown properly. You need to type "/stop" or "stop" into the console and let it save everything.

**Comment by maxlehot1234** [comment]
Yeah I know that, but imagine this situation:

The server run perfectly and something make it freeze and stop instantly. players will lost their progress since the world and everything are not save regulary ( example )

Its not a big deal, but I am sure other people will report this in the future when aOneBlock will be used a lot.

**Comment by tastybento** [comment]
I will point you to this resource I found about world saving. https://shockbyte.com/billing/knowledgebase/128/How-to-Configure-Autosaving-of-Your-Minecraft-World.html

BentoBox also provides a periodic saving of databases in the BentoBox config.yml to help recover info if a server crashes.

But these are to protect against crashes, not admins killing the server without shutting down, so try to shutdown properly.
