### ISSUE TITLE
Exploding Creeper

### ISSUE THREAD

**Issue by DrakMC** [BentoBoxWorld/AOneBlock#239]
### Expected behavior

When a player clicks on a creeper with a flint and steel on a player's island it cancel the event.

### Observed/Actual behavior

When a player right clicks on a creeper with flint and steel, the creeper explodes and destroys the player's island.

### Steps/models to reproduce

1. Click on creeper with flint and steel
2. Creeper explodes and destroys the blocks on the player's island

### BentoBox version

1.19.0

**Comment by tastybento** [comment]
Creeper griefing is only to prevent visitors from doing this. If a player does it to themselves, then it will blow up like normal. So, I don't see why this is a bug because it's what is supposed to happen. Am I missing something?

**Comment by amarcais53** [comment]
he was saying that if a player who is visitor on the island right click on a creeper with a flint and steel even with the flag off the creeper will blow and destroy the island , so a visitor can destroy a insland , i got that bug too and fixed it with worldguard by disabling creeper explosions
@tastybento
