### ISSUE TITLE
[BUG] No ./ob gui open after pressing ESC before choosing an island to start

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#24]
#### Describe the bug

If a player use ./ob and press ESC and ./ob again, the GUI will not open to allow him to choose an island to start, but he see this in the chat:
![image](https://user-images.githubusercontent.com/5159244/80655097-d8a39180-8a4b-11ea-9ad6-4ddf70017768.png)
Téléportation en cours = Teleportation in progress

Its like if the pluginw as not able to reopen the GUI, since it think that the player alreay had an island which is false.

#### Steps to reproduce the behavior

No idea, sorry for that :(

#### Expected behavior

The GUI should not be supposed to react like that. It should open the GUI to allow the player to choose his start island

##### BentoBox Version (Mandatory)

```
[17:14:32 INFO]: Running PAPER 1.15.2.
[17:14:32 INFO]: BentoBox version: 1.12.0
[17:14:32 INFO]: Database: JSON
[17:14:32 INFO]: Loaded Game Worlds:
[17:14:32 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[17:14:32 INFO]: Loaded Addons:
[17:14:32 INFO]: AOneBlock 1.1.5 (ENABLED)
[17:14:32 INFO]: Border 1.0.7 (ENABLED)
[17:14:32 INFO]: Challenges 0.8.1 (ENABLED)
[17:14:32 INFO]: Chat 1.0.5 (ENABLED)
[17:14:32 INFO]: Level 1.9.3 (ENABLED)
[17:14:32 INFO]: Limits 1.9.4 (ENABLED)
[17:14:32 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (22): AsyncWorldEdit, AutoPickup, BentoBox, CMI, DeluxeChat, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, PlaceholderAPI, ProtocolLib, SkinsRestorer, UltraCustomizer, Vault, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard

```
 
Thanks and let me know if you have a hint for that.

**Comment by tastybento** [comment]
I can't replicate this right now. I assume you have created multiple one-block blueprints for players to choose from? Does this happen every time?

Make sure the player is fully deleted `/oba delete (player)` and then have them create an island.
Also, have a look in the console and see if there are any errors.

**Comment by maxlehot1234** [comment]
Yeah I create a new blueprint.

Now It works. I will close it and let you know if I am to replicate it again and let you know
