### ISSUE TITLE
Can't break magic block

### ISSUE THREAD

**Issue by ifxory-plugins** [BentoBoxWorld/AOneBlock#240]
### Expected behavior

Block should break & drop some stuff.

### Observed/Actual behavior

Player can't break block, event is cancelled.

### Steps/models to reproduce

No exceptions are thrown and displayed in console.
1. Create island as default group (Luckperms)
2. Break your magic block for some time
3. You can't anymore break your block

### BentoBox version

Running Invalid (Pufferfish) 1.18.1
BentoBox Version 1.19.0
Database JSON
Loaded Game Worlds
oneblock world: Overworld, Nether
Loaded Addons
AOneBlock 1.9.0 (ENABLED)
Chat 1.1.4 (ENABLED)
Likes 2.1.1 (ENABLED)
Warps 1.11.2 (ENABLED)

### Plugin list

(22) AuctionMaster, BentoBox, Chatty, Citizens, DecentHolograms, DeluxeMenus, Essentials, EssentialsSpawn, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), KillerMoney*, LuckPerms, MyCommand, PlaceholderAPI, ViaBackwards, ViaRewind, ViaVersion, WorldGuard, XConomy

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/AOneBlock/issues/209
