### ISSUE TITLE
Make oneblock generated blocks give MCMMO EXP.

### ISSUE THREAD

**Issue by ClickErrorxD** [BentoBoxWorld/AOneBlock#246]
### Is your feature request related to a problem?

It's related to a problem because it voids a feature(s) from another popular plugin.
I would like AONEBLOCK to generate blocks as natural in order for MCMMO to be used on blocks such as ores and logs. (Mining and WoodCutting skills.)

### Describe the solution you'd like.

Basically, do what the author of McMMO said.
![image](https://user-images.githubusercontent.com/87890013/163916196-4d92e836-95d7-49a7-9b41-4efc5f58a9ff.png)
![image](https://user-images.githubusercontent.com/87890013/163916216-9ff34876-812a-472e-84bb-1bcb171f7f72.png)

In order to allow XP to be given for skills in McMMO, hook into their blocktracker API and make the blocks appear as natural.

### Describe alternatives you've considered.

No alternatives as this is out of my league.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
You have two options:
- disable `drop-on-top` option in aoneblock config
- update to latest dev version (ci.bentobox.world)
