### ISSUE TITLE
[New Feature] Reduce mobs drop in phases

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#25]
#### Is your feature request related to a problem?

My friend and I break 110 blocks and we got all of these passive mobs. Its fine, but it make the gamemode to easy I think.

#### Describe the solution you'd like us to implement.

Add something that can limit the amount of passive and agressive mobs can spawn per phase

Look at this:
![image](https://user-images.githubusercontent.com/5159244/80656670-b6ac0e00-8a4f-11ea-8276-1fd9b1af25a2.png)

Quite insane :P

Thanks again

**Comment by maxlehot1234** [comment]
Right now at Phase 2 (Underground) its like 1 zombie each 4-5 blocks. Its just too much seriously. (My point and my friend point too)

Please decrease them.

**Comment by tastybento** [comment]
You can configure the probabilities for mob spawns yourself using the oneblocks.yml file. 

Thanks for the feedback on the game play though. I might reduce it in the default settings.

**Comment by maxlehot1234** [comment]
Mobs spawn change are count in the block spawn chance too?

If I set mobs spawn to like 10-15 instead of 400, they will spawn lot less than the default ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tastybento** [comment]
Yes. You can use the `/obadmin sanity` to display a sanity check of the phase probabilities in the console.

If you come up with a better set than default then let me know what you recommend and maybe we'll change the default settings.

**Comment by maxlehot1234** [comment]
@tastybento Thanks for the command, but I got a weird message in the chat when I run it:
![image](https://user-images.githubusercontent.com/5159244/80854193-1814de00-8c04-11ea-8e8c-d6d6fbd4df3b.png)

I will for sure edit the default config to make it better to fit my needs. It will probably doesn't fit the need of all server owners.
