### ISSUE TITLE
[New Feature] Prevent a chest to be break if something was in ti

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#26]
#### Is your feature request related to a problem?

Prevent a chest to be broken if something was in it.

#### Describe the solution you'd like us to implement.

Maybe a config option true/false to let the server owner the choice for this?

This can add a new thing on the server.

Thanks to read my suggestion.

**Comment by tastybento** [comment]
Why do you think this is needed?

**Comment by maxlehot1234** [comment]
It can be a good thing to implement and prevent players to destroy it by error for example and lost items.

Imagine a new player that start, a chest spawn and he break it and lost its content.

Yeah they need to break blocks "slowly" and check the block that spawn, but if they are like 2-3 players to break the same block with a pickaxe and than a chest spawn... tadammm, the chest break almost instantly and items are gone.


But if the chests cant be break (or a island flag so the island owner can trigger this on/off) it will fix that ;) Useful if they want to learn the mechanics first. They can enable it after if they want.

**Comment by TNTUP** [comment]
I can confirm, that breaking the chest with stuff inside (the magic block) the items are lost
