### ISSUE TITLE
ability to disable the dynmap marker setup

### ISSUE THREAD

**Issue by MelonCraftDE** [BentoBoxWorld/AOneBlock#263]
### Is your feature request related to a problem?

Yes. 
Because they are force-created, no way around, they keep getting generated.

### Describe the solution you'd like.

a simple config entry

disable_dynmap_hook=true

or something like that.

To disable the Dynmap Hook, or just he marker setup.

### Describe alternatives you've considered.

no alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
Dynmap is disabled by bentobox.
