### ISSUE TITLE
water spawns on the block if there is already water

### ISSUE THREAD

**Issue by hribik100** [BentoBoxWorld/AOneBlock#265]
### Expected behavior

when a water mob spawns and there is water there will be no watter spawned

### Observed/Actual behavior

when a water mob spawns a water source is spawned if there is an acual water (i tried flowing water witch is enough for the mob)

### Steps/models to reproduce

just putt a bucket of water one two blocks away from the oneblock and mine in the ocean phase to spawn a mob

### BentoBox version

![image](https://user-images.githubusercontent.com/50539591/175806359-18157ee6-0373-4017-863d-799634244c24.png)

### Plugin list

![image](https://user-images.githubusercontent.com/50539591/175806377-db2e0b84-66d0-489d-bd70-d44e9c29e0e3.png)

### Other

the bentobox plugins and other plugins should interfere

**Comment by BONNe** [comment]
You can disable water spawning in the settings:
https://github.com/BentoBoxWorld/AOneBlock/blob/develop/src/main/resources/config.yml#L292-l293
