### ISSUE TITLE
DecentHolograms Integration 

### ISSUE THREAD

**Issue by Razorxd1993** [BentoBoxWorld/AOneBlock#266]
### Is your feature request related to a problem?

-

### Describe the solution you'd like.

Hi is it possible to add an integration for DecentHolograms? I do not use holographic displays, decentHolograms has Note Features :)

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
We now do holograms using the native API, so no need for plugins.
