### ISSUE TITLE
A flag(config option too?) for blocks being deleted upon mob spawn.

### ISSUE THREAD

**Issue by ClickErrorxD** [BentoBoxWorld/AOneBlock#268]
### Is your feature request related to a problem?

Yes, 100%.
We are hoping to get this added as Bentobox can break multiple items from other plugins we use.

Information on this can be found here @ this bug report: https://github.com/BentoBoxWorld/AOneBlock/issues/267

### Describe the solution you'd like.

I think it'd be helpful if we can CHOOSE whether or not the bentobox deletes blocks within the oneblock's radius.

This can be done via a config option, island flag (so it's player's choice, which is always amazing!) and or an event... however, not everyone can use apis/events, as not everyone can code... so the first 2 will be the most helpful to me/our server.

### Describe alternatives you've considered.

Reporting it... as it's hardcoded, we cannot change this via config or even island flags.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

We reported the issue that is causing us to suggest a fix/workaround for this issue. The issue report can be found above.

**Comment by tastybento** [comment]
Done in #314
