### ISSUE TITLE
[New Feature] Implement a respawn kit

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#27]
#### Is your feature request related to a problem?

Is it possible to implement a respawn kit with limited items in it like:
- Wooden_pickaxe
- Wooden_axe
- Workbench

This will allow "new" players to get something when they respawn after being kill or after they "jump" in the void.

Thanks again.
Sorry for the spam.

**Comment by maxlehot1234** [comment]
I try using CMI plugin but it don't work, maybe because the player won't respawn correctly inside aoneblock plugin or anything else.

Its weird, but if you can implement a config for this, it would be really, really cool. This thing will be an optionnal setting of course.

Thanks again @tastybento @Poslovitch

**Comment by tastybento** [comment]
This will be provided by this PR on BentoBox: https://github.com/BentoBoxWorld/BentoBox/pull/1374
