### ISSUE TITLE
Instant Block Break

### ISSUE THREAD

**Issue by DrakMC** [BentoBoxWorld/AOneBlock#270]
### Expected behavior

Blocks should not be destroyed instantly.

### Observed/Actual behavior

Currently sometimes players can destroy blocks instantly as with creative mode.

Video: https://medal.tv/games/minecraft/clips/cz1oyLVsr3KfS/1ft5ItYoHBEF?invite=cr-MSxMY1gsNDgwMDQwOTEs

### Steps/models to reproduce

I don't know exactly when it happens. 

### BentoBox version

1.20.0

**Comment by BONNe** [comment]
I think this issue was fixed in the latest dev version.
