### ISSUE TITLE
BENTOBOX doesn't stop users from access the menu of WildStacker Spawners.

### ISSUE THREAD

**Issue by ClickErrorxD** [BentoBoxWorld/AOneBlock#271]
### Expected behavior

For users to not get access to the menu's of this Spawner Plugin.

### Observed/Actual behavior

Basically, any user within our AOneblock Bentbox world can access other user's spawner's on their island by simply going to other player's islands and shift+right-clicking it and heading to the menus of your choice.

### Steps/models to reproduce

You need two accounts or two people.

Place a spawner on the first accounts island.
Use the other account and make it go to the island with the spawner.
Take the account of step 2 above and shift+right-click the spawner.
Optional, literally enter the amounts menu and click the red panes to take them.

### BentoBox version

![image](https://user-images.githubusercontent.com/87890013/178162108-c426bb4e-8a58-417a-862f-6e7b3f7ef50f.png)

### Plugin list

Plugins (5): BentoBox, Essentials, LuckPerms, Vault, WildStacker

### Other

Additional Information
You can view the proof/evidence of this bug here. https://youtu.be/oQhiRuSBTSA

I do not know which side this plugin is issued by, [WildStacker](https://github.com/BG-Software-LLC/WildStacker/issues) or Bentobox AOneblock. I reported it here and on WildStacker's issues.

**Comment by BONNe** [comment]
Sorry, it is nor BentoBox nor AOneBlock issue.

GUI protection is either WildStackers or any other plugin/addon job.

In our download site you can download WildStackersHook that has the protection for GUIs, if you do not get any answers from them.

**Comment by ClickErrorxD** [comment]
> Sorry, it is nor BentoBox nor AOneBlock issue.
> 
> GUI protection is either WildStackers or any other plugin/addon job.
> 
> In our download site you can download WildStackersHook that has the protection for GUIs, if you do not get any answers from them.

But that also adds settings we can't use. Like allow users to stop mobs from stacking? That'll just cause client and server lag.

**Comment by BONNe** [comment]
All BentoBox flags are optional. You can hide them from users.
These options exist because someone find them useful.

**Comment by ClickErrorxD** [comment]
> All BentoBox flags are optional. You can hide them from users. These options exist because someone find them useful.

Ah right! I was thinking back to when I asked about the shulker setting... i thought all player's had viewed what I was seeing. This makes since. WS has yet to reply, so ill check out the add-on. Thank you BONNe!
