### ISSUE TITLE
Wildstacker Hook doesn't work for barrels of WS.

### ISSUE THREAD

**Issue by ClickErrorxD** [BentoBoxWorld/AOneBlock#274]
### Expected behavior

For player's not to have the ability to take blocks from wildstacker barrels / stacked block.

### Observed/Actual behavior

Player's can freely withdraw blocks from wildstacker stacked/barreled blocks, despite not having access to the island.

### Steps/models to reproduce

Get WildStacker...
Enable Wildstacker barrels and add stackable blocks to the config. (we used netherite blocks)
Get the Wildstacker hook.
Get 2 accounts, one make an island, the other, get tp'd to the island of the other account. Make sure not to have any permissions.
Then right-click the blocks that are stacked...

### BentoBox version

![image](https://user-images.githubusercontent.com/87890013/180111360-118d4bf9-2e62-4220-ba77-68d8fb8978f3.png)

### Plugin list

Essentials, Bentobox, Wildstacker and Vault.

### Other
https://youtu.be/vPmUffK7ZcM

**Comment by ClickErrorxD** [comment]
Edit: The hook blocks the menu of barrels. However, if you just right-click the player's stacked blocks, it just deducts it...

**Comment by ClickErrorxD** [comment]
https://youtu.be/vPmUffK7ZcM

**Comment by ClickErrorxD** [comment]
What does closed this as completed mean?

**Comment by BONNe** [comment]
https://github.com/BONNePlayground/WildStackerHook/issues/2

AOneBlock has nothing to do with WildStackerHook. And you already created a report in WildStackerHook repo.
