### ISSUE TITLE
Phase completed counted twice in the lifetime count's

### ISSUE THREAD

**Issue by Bastxz** [BentoBoxWorld/AOneBlock#276]
### Expected behavior

After the phase is completed, the phases are counted twice in the lifetime count.
Example: 11000 = 22000, 22000 = 44000 and so on

### Observed/Actual behavior

As described above

### Steps/models to reproduce

Just complete the phases.

### BentoBox version

BentoBox-1.20.1

**Comment by dule0004** [comment]
I have same issue 
https://github.com/BentoBoxWorld/AOneBlock/issues/278
