### ISSUE TITLE
[New Feature] Add ./ob in the falling-banned-commands config part by default

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#28]
#### Is your feature request related to a problem?

The default config file doesn't had the ./ob command into the falling-banned-commands config part.
This allow player to ./ob when they falling and respawn in the teleport point of their island without losing their items

#### Describe the solution you'd like us to implement.

Add ./ob in the falling-banned-commands config part by default

This thing will prevent new server owner to have to disable it manually just in case.

**Comment by maxlehot1234** [comment]
EDIT: If I put it in the falling-banned-commands config part and reload, players can still use the command.

If they use it really fast, they can stay alive and lost 1-2 hearts. (NOT NORMAL)
BUT
If they are slow, they will be killed and go back to the island (normal)

**Comment by tastybento** [comment]
Do `/oba settings`, look at the world settings and find the feather icon:

<img width="521" alt="Screen Shot 2020-04-29 at 8 50 54 PM" src="https://user-images.githubusercontent.com/4407265/80670296-62a72680-8a5b-11ea-8cfa-ea6eeae6a141.png">

Select "Active". This will prevent players from teleporting when falling. No need to add it to the commands.

I recommend you look through all the settings that are available.
