### ISSUE TITLE
With all config open!BUT Unable to generate the end gate

### ISSUE THREAD

**Issue by Finaplot** [BentoBoxWorld/AOneBlock#286]
### Expected behavior

I opened allow-end in Bukkit and allow-nether in server.properties, including generate and islands in config, It can generate the end to ground transmission gate

### Observed/Actual behavior

I opened allow end in Bukkit and allow other in server.properties, including generate and islands in config, Unable to generate the end gate

### Steps/models to reproduce

No error reported

### BentoBox version

Running PAPER 1.18.2
BentoBox version 1.20.1
Database JSON
Loaded Game Worlds：
oneblock_world (OneBlock) : Overworld, Nether, The End
Loaded Addons：
AOneBlock 1.10.1 (ENABLED)
Biomes 2.0.0 (ENABLED)
 Challenges 1.0.0 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
 Level 2.9.0 (ENABLED)
Limits 1.19.0 (ENABLED)
MagicCobblestoneGenerator 2.4.0 (ENABLED)
 Warps 1.12.0 (ENABLED)

### Plugin list

Plugins (2): BentoBox, PlaceholderAPI

### Other

I'm from China, so my English is not very good, please forgive me

# AOneBlock Configuration 1.10.1
aoneblock:
  command:
    island: ob
    admin: obadmin
    new-player-action: create
    default-action: go
    count-command: count
    phases-command: phases
    set-count-command: setCount
    respawn-block-command: respawnBlock check
  placeholders:
    scale-symbol: 
world:
  friendly-name: OneBlock
  world-name: oneblock_world
  difficulty: NORMAL
  spawn-limits:
    monsters: 25
    animals: 8
    water-animals: 3
    ambient: 10
    ticks-per-animal-spawns: 400
    ticks-per-monster-spawns: 2
databases and worlds.
  distance-between-islands: 600
  protection-range: 100
  start-x: 0
  start-z: 0
  offset-x: 0
  offset-z: 0
  island-height: 80
  use-own-generator: false
  sea-height: 0
  max-islands: 0
  default-game-mode: SURVIVAL
  default-biome: PLAINS
  default-nether-biome: NETHER_WASTES
  default-end-biome: THE_END
  ban-limit: -1
  nether:
    generate: true
    islands: true
    roof: false
    spawn-radius: 0
    create-and-link-portals: false
  end:
    generate: true
    islands: true
    create-obsidian-platform: false

**Comment by Finaplot** [comment]
What I can guarantee is that the world and islands have been created!

**Comment by BONNe** [comment]
https://www.youtube.com/watch?v=-_zVGFMgGbs

**Comment by Finaplot** [comment]
I made sure I successfully built,and in another test, I placed ''end_ gateway "went inside, but instead of being transmitted to THE_END, it was transmitted to the empty island of other players,If allowed, can I upload a video to prove what I saw

**Comment by BONNe** [comment]
Sure, you can do it.

**Comment by Finaplot** [comment]
Due to the size limit of the uploaded video, I will send it to your email address to bonne@bonne.id.lv

**Comment by BONNe** [comment]
Very sorry for the late answer.

I am not 100% sure why the portal operates like that. Maybe it is because you use END_GATEAWAY and not END_PORTAL, but both should work in the same way.

Could you translate the messages you receive when you entered teleport?

Also, is the player teleported to the world spawn point? It would indicate that player does not have a valid target spot for teleportation. 

Did end-islands were enabled when you created island or you enabled end world and end  islands after your island was created?
As in that situation, the player does not have a place to teleport to the end. It can be fixed by enabling: `create-missing-nether-end-islands`

Also, there is an option to create an obsidian platform in the end-world when the player teleports (like in vanilla). (`create-obsidian-platform`)

**Comment by Finaplot** [comment]
Translate:
After entering the end, what is said in the chat bar is
"You have left your island"
"You have entered the island of Im_Martian811"
NO:
Players haven't teleported to the world rebirth point. For example, when I died, I teleported to my own island
As for the world rebirth point, except the oneblock world, the rebirth point of other worlds is in the world "zc"
Create:
I'm afraid it's hard to explain this problem. I opened the option before I created the island, but at the time of feedback, end was generated normally, but could not be transmitted. Until the end of recent days, the local dimension turned into the main world dimension, which made me confused
create-missing-nether-end-islands and create-obsidian-platform:
I have tried to open both options, but they are useless
Thank you very much for taking the time to answer my questions

**Comment by Finaplot** [comment]
Especially important, the portal of my other world is working!

**Comment by Finaplot** [comment]
I think I can do a test to determine where the problem is

**Comment by Finaplot** [comment]
![image](https://user-images.githubusercontent.com/99035346/196025745-1b2ddec2-eb8f-47b2-85a1-8f73555e7e94.png)

**Comment by BONNe** [comment]
From an image, it is hard to say if it is built correctly, as the direction NORTH-SOUTH and EAST-WEST look the same, while for the portal to generate it is required to be correct.
![ender-portal](https://user-images.githubusercontent.com/1344358/196031362-9519d72f-3ffe-4ae3-9f0f-12619ead751e.png)

The frame block should say that it is facing opposite to the direction player is looking. You can check it with F3 menu.

And there are only 2 reasons why the portal is not generating:
- Portal is created incorrectly.
- The plugin is blocking the portal to generate.

Inside BentoBox we do not have anything that would prevent the portal from generating, so it may be another plugin that does it if your portal is built correctly.

**Comment by Finaplot** [comment]
I checked according to your method and found that there was no error in the construction of the portal, so I am sure that other plug-ins should have prevented the generation of the portal
