### ISSUE TITLE
AOneblock lag

### ISSUE THREAD

**Issue by FranzWolff** [BentoBoxWorld/AOneBlock#287]
### Expected behavior

To not lag & do the task very quickly

### Observed/Actual behavior

Have many players online & leaving/joining their islands/the server.

### Steps/models to reproduce

 https://cdn.discordapp.com/attachments/310623455462686720/1036283021977976982/unknown.png

### BentoBox version

Latest, 1.21.1

### Plugin list

BentoBox, essentials, vault

### Other

I found that https://github.com/BentoBoxWorld/BentoBox/search?q=copyChunkDataToChunk this method is the one that lags
probably because a chunk is not loaded and forces paper to load it on the main thread, paper has an async chunk loader.

**Comment by tastybento** [comment]
Thanks for the pointers. This code is run when there is an island reset. Do you have any of those happening or queued up? I'd like to confirm a bit more about the lagging, like can you share the link to the actual lag report?
