### ISSUE TITLE
Creeper Grief

### ISSUE THREAD

**Issue by DrakMC** [BentoBoxWorld/AOneBlock#292]
### Expected behavior

The creeper explodes but does not destroy the player's island or the creeper does not explode at all.

### Observed/Actual behavior

Creeper explodes on a player who visits another player's island and damages their island

### Steps/models to reproduce

1. Go to a creeper on another player's island
2. Creeper explodes and damages the island

### BentoBox version

Running Invalid (PUFFERFISH) 1.19.2.
BentoBox version: 1.21.1
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether*
Loaded Addons:
AOneBlock 1.11.0 (ENABLED)
Biomes 2.0.0 (ENABLED)
Challenges 1.0.0 (ENABLED)
Chat 1.1.4 (ENABLED)
Level 2.9.0 (ENABLED)
Limits 1.19.0 (ENABLED)
Warps 1.12.0 (ENABLED)

**Comment by BONNe** [comment]
There is a flag name CREEPER_GRIEFING.

This flag protects islands from visitor ignited creepers.

**Comment by DrakMC** [comment]
Thanks
