### ISSUE TITLE
Creeper explode

### ISSUE THREAD

**Issue by DrakMC** [BentoBoxWorld/AOneBlock#294]
### Expected behavior

Creeper won't explode on player's island

### Observed/Actual behavior

Creeper's can be ignited with flitn and steel. After that, the creeper will explode and destroy other player's island.

### Steps/models to reproduce

1. Go to creeper
2. Ignite the creeper with flint and steel
3. The creeper exploded and destroyed player's island

### BentoBox version

Running Invalid (PUFFERFISH) 1.19.2.
BentoBox version: 1.21.1
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether*
Loaded Addons:
AOneBlock 1.11.0 (ENABLED)
Biomes 2.0.0 (ENABLED)
Challenges 1.0.0 (ENABLED)
Chat 1.1.4 (ENABLED)
Level 2.9.0 (ENABLED)
Limits 1.19.0 (ENABLED)
Warps 1.12.0 (ENABLED)

**Comment by tastybento** [comment]
Creeper griefing protection should be on by default, but you should check that it is. Use the admin command and settings. Here's the setting:
<img width="555" alt="Screenshot 2022-12-04 at 8 47 39 PM" src="https://user-images.githubusercontent.com/4407265/205551850-8c505d1e-6380-49b3-bee1-2bf996d26db1.png">

**Comment by DrakMC** [comment]
This option will prevent from destroying blocks from exploding creeper but it doesn’t work when I right click on a creeper with flint and steel.
