### ISSUE TITLE
Placeholder: scale and % of a specific phase 

### ISSUE THREAD

**Issue by Dreamx7** [BentoBoxWorld/AOneBlock#295]
**Description**

I would like to have a variable of a scale and % of a precise phase.
For example I am at 10% of the underground phase, but I am also at 5% of the mountain phase.
Here is a screen of the result that would give
Underground; https://zupimages.net/up/22/48/ik2u.png
Mountain: https://zupimages.net/up/22/48/lw9h.png

**Placeholder**: `%aoneblock_#namephase#_done_scale% and %aoneblock_#namephase#_percent_don% `

**Comment by tastybento** [comment]
I don't understand. How can you be in two phases at the same time?
There is a scale placeholders and percentage placeholders if that's what you are looking for: https://docs.bentobox.world/en/latest/gamemodes/AOneBlock/#placeholders
