### ISSUE TITLE
Super Flat World loads near created islands

### ISSUE THREAD

**Issue by UsefullSpoon** [BentoBoxWorld/AOneBlock#296]
### Expected behavior

new player makes island, 
island generates,
no blocks near one block island

### Observed/Actual behavior

new player makes island,
island generates
flat world generates at bottom and outside island area

### Steps/models to reproduce

1: create island
2: island was created
3: world loads around you (did not happen to OP's)

### BentoBox version

Running PAPER 1.19.2
BentoBox version: 1.12.1
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether, The End
Loaded Addons:
AOneBlock 1.11.0 (ENABLED)
Challenges 1.0.0 (ENABLED)
Level 2.9.0 (ENABLED)
MagicCobblestoneGenerator 2.4.0 (ENABLED)

### Plugin list

  [Tue 16:18:50 INFO ] Plugins (77): AdvancedPortals, AntiPopup, ArmorStandTools, AuctionHouse, AutomaticBroadcast, AutoSell*, Bank, BentoBox, BKCommonLib, BuildMoney, ChatGames, Citizens, CommandLog*, Core, CoreProtect, CraftEnhance, CraftingStore, CrashAPI, CrazyCrates, DecoHeads*, Denizen, DiscordSRV, EconomyShopGUI, EnchantmentSolution, Essentials, EssentialsSpawn, EvenMoreFish, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GriefPrevention, GSit, HolographicDisplays, HPWP, IllegalStack, ImageOnMap, LootChest, Lores*, LuckPerms, mcMMO, My_Worlds, MyCommand, NexEngine, NotQuests, OpenInv, PlaceholderAPI, Plan, PluginManager, ProtocolLib, QuickShop, RandomLootChest*, RandomTeleport, RealScoreboard, RewardsLite, Sellwand, Sentinel, ServerListPlus*, SkinsRestorer, sleep-most, SnowballDamage*, spark, StackMob, SuperChairs, SuperVanish, TabList, TokenManager, ToolAndFoodFX*, TreysDoubleJump, Vault, VeinMiner, VentureChat, ViaVersion, Votifier, VotingPlugin, Vouchers, WorldGuard, XConomy

**Comment by BONNe** [comment]
Can you check if any of these situations applies to you:
https://docs.bentobox.world/en/latest/FAQ/#superflat-chunks-are-generating-in-my-worlds

**Comment by tastybento** [comment]
If this is still an issue, let us know otherwise closing.
