### ISSUE TITLE
Top Placeholder

### ISSUE THREAD

**Issue by Verzante** [BentoBoxWorld/AOneBlock#299]
For Oneblock plugin: A placeholders to display top phase and name of the player

%aoneblock_top_island_phase_#rank#%
%aoneblock_top_island_phase_name_#rank#%

**Comment by Verzante** [comment]
> What would be the definition of "top phase"?

Top phase is meant as top island level. Same as already existing placeholder "%aoneblock_my_island_phase%" -> so this one but for the top statistics as I wrote

**Comment by tastybento** [comment]
I'm still a bit confused. Do you mean top as in a Top Ten, where the the players with the highest block counts are ranked and you can obtain them via these placeholders? If so, then this is more a request for a ranking system for players based on their block count.  This potentially could be done, but maybe as a different add-on, like the Level add-on. Also, it's possible to go through the phases multiple times, so the phases can be repeated.

**Comment by Verzante** [comment]
> I'm still a bit confused. Do you mean top as in a Top Ten, where the the players with the highest block counts are ranked and you can obtain them via these placeholders? If so, then this is more a request for a ranking system for players based on their block count. This potentially could be done, but maybe as a different add-on, like the Level add-on. Also, it's possible to go through the phases multiple times, so the phases can be repeated.

Yes, top ten placeholders, but not for how many blocks players mined, but for the phase levels. We don’t use phase repetition. I will give the placeholder examples:

Default: 

%aoneblock__island_phase_lvl_top_<number>% and %aoneblock__island_phase_name_top_<number>%

In use:

%aoneblock__island_phase_lvl_top_1% / %aoneblock__island_phase_name_top_1%
%aoneblock__island_phase_lvl_top_2% / %aoneblock__island_phase_name_top_2%

and so on...

If the player with highest phase lvl is named "Verzante" and his phase level is "50" the placeholders would return

50 / Verzante

same goes for the second highest phase player

**Comment by tastybento** [comment]
Okay, I understand.

**Comment by tastybento** [comment]
This will be done with another Addon that is in progress: https://github.com/BentoBoxWorld/TopBlock

**Comment by tastybento** [comment]
Okay, this should be done now. You will need the latest AOneBlock version to use it, version 1.12.3, just released.
Snapshot can be downloaded from: https://ci.codemc.io/job/BentoBoxWorld/job/TopBlock/
Placeholders can be found here: https://github.com/BentoBoxWorld/TopBlock#placeholders
