### ISSUE TITLE
[New feature] Implement an island map

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#30]
#### Describe the solution you'd like us to implement.

Is it possible for you to implement a map that allow players to display it on a frame for example on their island to "Show-off" their island to visitor?
This can add somthing lese to them.
Also do not give them easily. Allow us to put it in a RARE chest to make it rare

#### Describe alternatives you've considered.

I try to give myself a filled_map but doesn't work. I thinks its something you need to develop.

I stop for today :P Too many tickets "cause" of me.
I love the idea and since you develop a pluign, its lot more easier to configure than a map and java file ;)

Thanks in advance

**Comment by tastybento** [comment]
If you give yourself a map and then look at it, it will fill in with your surroundings. Of course, if you only have 1 block, then it will be tiny. Here's a picture from a bigger BSkyBlock start island. I've seen players put these up on their islands over the years.
<img width="714" alt="Screen Shot 2020-04-29 at 8 57 52 PM" src="https://user-images.githubusercontent.com/4407265/80670598-3049f900-8a5c-11ea-8019-e40aa173d6ef.png">
