### ISSUE TITLE
Got teleported back into main world when fall into the lobby

### ISSUE THREAD

**Issue by GuavaJovanJambu** [BentoBoxWorld/AOneBlock#301]
### Expected behavior

Title, when i fell into the void at oneblock world, i was back got teleported into my main lobby or main worlds. Pls help me with this issue

### Observed/Actual behavior

Got teleported to different world when fell into the void

### Steps/models to reproduce

1. Go to your own ob islands
2. 2. Fell into voids
3. Got teleported back into main world

### BentoBox version

Bento box 1.21.1

### Plugin list

Plugins (41): BentoBox, BetterRTP, BlueMap, ClearLag, CombatPlus, CommandPanels, CrazyEnchantments, CustomCrates, DeadlyDisasters, DeluxeHub, DiscordSRV, EconomyShopGUI, Essentials, Factions, floodgate, Geyser-Spigot, GriefPrevention, HolographicDisplays, JoinAvatar*, LuckPerms, MiniMOTD, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MultiWorldMoney*, NametagEdit, PerWorldPlugins, PlaceholderAPI, PowerRanks, PvPManager, ServersNPC, SkinsRestorer, Spawntp, SuperbVote, TAB, Vault, ViaBackwards, ViaVersion, Votifier, WorldEdit, WorldGuard

**Comment by BONNe** [comment]
You can enable `ISLAND_RESPAWN` flag in `/[admin_cmd] settings`

Also, if you sleep in bed, you will respawn in it :)

**Comment by GuavaJovanJambu** [comment]
Oh, i will try it

**Comment by GuavaJovanJambu** [comment]
I already try that and enable that but still spawn on other worlds :(

**Comment by tastybento** [comment]
Check AOneBlock's config.yml for:
```
on-respawn: []
```
to see if you have any commands there. These are run when the player respawns.

Other than that, you must have a plugin that teleports people back to the main worlds when they die, which is doing this, so maybe there's a clash. Which one do you use for that? I recommend trying a server without that just to confirm that the player gets teleported back to their island.

**Comment by GuavaJovanJambu** [comment]
It say no commands at there, should i put a command or what?

**Comment by tastybento** [comment]
No, it's just if you had put one in there maybe that's why the player was going to another world. 

Like I said, your spawn plug-in must be overriding whatever we are doing. There's not much we can do here. Sorry.

**Comment by GuavaJovanJambu** [comment]
Oh okay, anyways thanks for the help :)
