### ISSUE TITLE
AOneBlock /ob phases for lower ranks not only Island owner 

### ISSUE THREAD

**Issue by Billabomb75** [BentoBoxWorld/AOneBlock#305]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Add in the option for /ob Phases to allow sub-owner to be able to change the phases on One Block

### Describe alternatives you've considered.

havent found any alternatives 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
I might be misunderstanding, but the phases command just shows you the phases of AOneBlock - it doesn't enable you to change them because phases are set for the whole game/world and everyone plays the same set of phases. So, this request does not really make sense. Or am I missing something?

**Comment by Billabomb75** [comment]
> I might be misunderstanding, but the phases command just shows you the phases of AOneBlock - it doesn't enable you to change them because phases are set for the whole game/world and everyone plays the same set of phases. So, this request does not really make sense. Or am I missing something?

So Island owner got the right after they finished the phases to change to what ever phase they want. All the other Team Members doesn't have access to it. They can how ever see it but not change it

**Comment by BONNe** [comment]
@tastybento there is set-count command integration with the phase panel.
However, set-count is allowed to be executed only by island owner.

**Comment by Billabomb75** [comment]
Yes, but i want the feature to be added that other Team members on your island (if they on Sub Owner level) to be able to change the phases as well

**Comment by tastybento** [comment]
@BONNe Aha, gotcha. 

I made the player's `setcount` command rankable, so it can be assigned to lower ranks than owner. So long as the player has the permission for the command, they should be able to change the phase, if they also have the rank set.

**Comment by Billabomb75** [comment]
> @BONNe Aha, gotcha. 
> 
> I made the player's `setcount` command rankable, so it can be assigned to lower ranks than owner. So long as the player has the permission for the command, they should be able to change the phase, if they also have the rank set.

Thanks a lot. Did you release a new update ?

**Comment by tastybento** [comment]
Yes, this is done.
