### ISSUE TITLE
Oneblock suggestion(s)

### ISSUE THREAD

**Issue by Fluxious-Sander-Silver** [BentoBoxWorld/AOneBlock#308]
### Is your feature request related to a problem?

The feature i would like to see are the following: 
1. Prestige feature
2. Island level colors
3. Extended protection size

### Describe the solution you'd like.

1. Meaning u can complete a cycle and that gives you a prestige point. So meaning u can get like 50 prestiges (cycles). Shouldnt be too hard to develop that I think. Then for its rewards. The Prestige points. A shop/gui with upgrades of spawn rate of npc's, island protection size etc.

2. Island levels should give the option to set a color to them. I use the Island levels as a way to show your "skill" in chat. example:
[12] [Plains] Sander: Test     << the 12 is the island level, I would like to have some sort of color gradation too it. So:
&7 [1]
&2 [2] etc.

3. Scrolls that extend the protection size of the island with for example +25
4. 

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
For the first suggestion, there is a cycle count that can be accessed by [placeholders](https://docs.bentobox.world/en/latest/gamemodes/AOneBlock/#placeholders):

- %aoneblock_my_island_lifetime_count%
- %aoneblock_visited_island_lifetime_count%

Also, this count is available via the API if some code needs it. You would need to have another plugin use that count and manage the rewards though.

For the third - there are admin commands to expand island range, so another plugin or approach should be able to run those. See https://docs.bentobox.world/en/latest/FAQ/#how-can-i-increase-a-players-island-size for info.
