### ISSUE TITLE
Cooldown feature when switching oneblock phases from menu

### ISSUE THREAD

**Issue by Lukevdh** [BentoBoxWorld/AOneBlock#309]
### Is your feature request related to a problem?

This would prevent a lot of spamming within this feature and is overall just something most servers would want to be able to chose.

### Describe the solution you'd like.

Add a cooldown on the /ob phases menu for people that can switch phases all the time. Also make it that we can set the cooldown ourselfs in seconds or ticks etc.

### Describe alternatives you've considered.

Maybe a cost per phase change would be cool? This way people need to grind a little to be able to switch again.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Nope! Thanks for looking into this and hopefully this will be added.

**Comment by tastybento** [comment]
Good idea. Added. Snapshot version is available on ci.bentobox.world.
