### ISSUE TITLE
First Time completion commands

### ISSUE THREAD

**Issue by ClickErrorxD** [BentoBoxWorld/AOneBlock#311]
### Is your feature request related to a problem?

Not exactly.

I would like this feature to be added because I would like to reward my player's for completing a phase, at least once. However, once they complete a phase, i would like them to not be able to just re-do the phase for the command/reward over and over.

### Describe the solution you'd like.

My solution seems very straight forward and ideal.
```  start-commands:
  - 'broadcast &c&l[!] &b[player] &fhas started their adventure.'
  end-commands:
  - 'broadcast &c&l[!] &b[player] &fhas completed the &d&n[phase]&f phase.'
  first-completion-commands: #only occurs on first completion.
  - 'broadcast &c&l[!] &b[player] &fhas completed the &d&n[phase]&f phase for the first time.'
```

This would add a new command section that would only run ONCE per player.

### Describe alternatives you've considered.

Asked in the support discord, got no other alternatives sent to me.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Okay, this is done. The additional config to the phases.yml is as follows:

```
  # These are run only the first time a phase is completed
  end-commands-first-time:
  - 'broadcast &c&l[!] &b[player] &fhas completed the &d&n[phase]&f phase for the first time.'
```

The snapshot can be found here: https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/317/

I'd appreciate it if you could verify it works as you expect.

**Comment by ClickErrorxD** [comment]
> Okay, this is done. The additional config to the phases. yml file is as follows:
> 
> ```
>   # These are run only the first time a phase is completed
>   end-commands-first-time:
>   - 'broadcast &c&l[!] &b[player] &fhas completed the &d&n[phase]&f phase for the first time.'
> ```
> 
> The snapshot can be found here: https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/317/
> 
> I'd appreciate it if you could verify it works as you expect.

I am unable to test this as I have cancelled my development server.. Is it worth the risk to try it on the live server?

**Comment by tastybento** [comment]
Hmm, you can try, but make backups.

For testing, I just run the server locally on my laptop and connect using "localhost". That's the best way to test out stuff.
