### ISSUE TITLE
After breaking blocks, new blocks are not generated.

### ISSUE THREAD

**Issue by q2784038931** [BentoBoxWorld/AOneBlock#313]
### Expected behavior

After breaking blocks, new blocks are not generated.

### Observed/Actual behavior

After breaking blocks, new blocks are not generated.

### Steps/models to reproduce

After breaking blocks, new blocks are not generated.

### BentoBox version

After breaking blocks, new blocks are not generated.

### Plugin list

After breaking blocks, new blocks are not generated.

### Other

After breaking blocks, new blocks are not generated.

**Comment by BONNe** [comment]
Please fill bugreprot correctly.

**Comment by q2784038931** [comment]
I want to solve problems。After breaking blocks, new blocks are not generated.I don't know much about English

**Comment by q2784038931** [comment]
Magic blocks will not continue to generate
