### ISSUE TITLE
Make suspicious sand and gravel work in oneblock generator

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/AOneBlock#325]
### Is your feature request related to a problem?

To make it possible with a brush to get items from suspicious sand/gravel, it will be more fun to get vanilla items. Now is making empty gravel and sand and impossible to get any item from them.

### Describe the solution you'd like.

Generated random items in suspicious sand/gravel by vanilla % and when brushing these blocks you can find them.

### Describe alternatives you've considered.

If this not be completed I should put these items (which you can only get from there suspis. sand/gravel) in missions rewards or market, or in the chest's where it will not be so convenient to get them and the joy of 1.20 brushing will not be in aoneblocke 

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Yes! I like this idea!

**Comment by BONNe** [comment]
Maybe it would be better as a separate addon?

Btw,  I am pretty sure you already can do it with data packs.

**Comment by tastybento** [comment]
To start, I am just going to make suspicious sand and gravel be able to generate the expected loot per the biome they are in.

**Comment by SirvydasS** [comment]
IDK if it's related with this commit, but with the latest build ([#360]) of AOneBlock is breaking the plugin, when breaking aoneblock main "block" its disappears and gives errors in the console:
Error log: https://pastebin.com/hj5SeGKq

**Comment by BONNe** [comment]
Please create new bug report.

**Comment by tastybento** [comment]
Tracking in #327 - due to refactor issues.
