### ISSUE TITLE
OneBlock phases intermix

### ISSUE THREAD

**Issue by Razorxd1993** [BentoBoxWorld/AOneBlock#326]
### Expected behavior

Unfortunately, I have the problem that my phases start to blend together from about the middle of the count.
So mobs and blocks from other phases appear that should only come in several next phases or already were.

### Observed/Actual behavior

-

### Steps/models to reproduce

Unfortunately it is not possible to reproduce

### BentoBox version

[20:16:59 INFO]: Ausführen von PAPER 1.20.1.
[20:16:59 INFO]: BentoBox version: 1.24.0
[20:16:59 INFO]: Datenbank: JSON
[20:16:59 INFO]: Geladene Spielewelten:
[20:16:59 INFO]: oneblock_world (OneBlock): Oberwelt, Nether, End
[20:16:59 INFO]: Geladene Addons:
[20:16:59 INFO]: AOneBlock 1.14.0-SNAPSHOT-b354 (ENABLED)
[20:16:59 INFO]: Biomes 2.2.0-SNAPSHOT-b250 (ENABLED)
[20:16:59 INFO]: Border 4.1.1-SNAPSHOT-b179 (ENABLED)
[20:16:59 INFO]: Chat 1.1.4 (ENABLED)
[20:16:59 INFO]: ControlPanel 1.13.1-SNAPSHOT-b60 (ENABLED)
[20:16:59 INFO]: DimensionalTrees 1.6.1-SNAPSHOT-b87 (ENABLED)
[20:16:59 INFO]: ExtraMobs 1.12 (ENABLED)
[20:16:59 INFO]: Level 2.11.0-SNAPSHOT-b540 (ENABLED)
[20:16:59 INFO]: Likes 2.4.0-SNAPSHOT-b96 (ENABLED)
[20:16:59 INFO]: Limits 1.19.1-SNAPSHOT-b316 (ENABLED)
[20:16:59 INFO]: MagicCobblestoneGenerator 2.5.1 (ENABLED)
[20:16:59 INFO]: Visit 1.7.0-SNAPSHOT (ENABLED)
[20:16:59 INFO]: Warps 1.13.0-SNAPSHOT-b350 (ENABLED)

### Plugin list

Paper Plugins:
EconomyShopGUI, WolfyUtilities

Bukkit Plugins:
AdvancedChests, AntiMapCopy, AutomaticBroadcast, Autorank, Baconize, BentoBox, BentoBox-AOneBlock, BentoBox-Biomes, BentoBox-Level, BentoBox-Likes, BentoBox-Limits, BentoBox-MagicCobblestoneGenerator, BentoBox-Visit, BentoBox-Warps, BetterHeads, BetterReports, BlockPiglinsTranformation, BottledExp, Bundle, BungeeTabListPlus
ChatColor2, ChestShop, Citizens, CMILib, ColoredPrefix, CommandBlocker, CommandPanels, CommandToItem, ConsoleSpamFix
CustomCrafting, DecentHolograms, *DisableJoinMessage, eBackup, Elevator, Essentials, EssentialsSpawn, etwSlots, ExcellentCrates, ExcellentEnchants, FarmControl, FilteredHoppers, HiveChecker, HomeGUI, HopperSorter, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, *InWartung, ItemEffects, ItemsAdder, JetsAntiAFKPro, KeepItems, KGenerators, LitePlaytimeRewards, LitMinions, LoneLibs, LuckPerms, Multiverse-Core, Multiverse-Portals, MyCommand, MyHomeRules, NBTAPI, NewbsCreative, NexEngine, NHGrinder, ntdLuckyBlock, OtherDrops, PlaceholderAPI, Plan, PlayerControl, PlugManX, ProtocolLib, RealScoreboard, RHSignItem, SetSpawn, Shopkeepers, *SimpleSit, sleep-most, TabCompleteFilter, TabTPS, TempFly, TradeSystem, TreeFeller, Tweakin, UltimateAutoRestart, Vault, VentureChat, ViaBackwards, ViaVersion, VillagerInventory, VoidGen, VoidTotem, Votifier, VotingPlugin, WorldBorderAPI, WorldEdit, worldedit-selection-viewer, WorldGuard, YamipaPlugin

**Comment by tastybento** [comment]
Hmm. That shouldn't happen. Some questions:

1. Did you customize the phases at all?
2. Does this happen with all players, or just one (or a few)? If just a few/one who has this issue?
3. Can you share your AOneBlock folder and BentoBox database folder? This will help me try and replicate the issue you are seeing (zip and drag and drop in this reply).

**Comment by Razorxd1993** [comment]
1. yes all phases have been customized by yourself
2. all players have this
3. uploaded
4. the error was reported to me only recently, unfortunately I do not know since when this exists. Yes I have only recently installed the latest update (about 2 weeks ago).
5. no matter, this occurs the first time you play through, as well as multiple times.

**Comment by Razorxd1993** [comment]
[AOneBlock+Database.zip](https://github.com/BentoBoxWorld/AOneBlock/files/12073536/AOneBlock%2BDatabase.zip)

**Comment by tastybento** [comment]
I can't see any issues with the phase files. Unfortunately, short of playing through a whole game myself, I cannot see a way to replicate this. What I need is the name/UUID of the player that is having an issue with this right now so I can "become" him and try and see if happens.

From the code though, I cannot see how this could happen. Each phase is loaded separately into phase objects that don't share any data. If a user's block count were to change to another phase then they would get a popup showing the new phase's name when they broke a block. This phase is then used to select a mob or block. Do players see a pop up showing the phase as changed?

If you could get a video of this happening it would be useful.

**Comment by Razorxd1993** [comment]
Good morning :)
So mainly it's noticed in at these UUID's that have reported it:

6c510ad0-5f33-4635-b473-2cc0ce5ff813
5115ea28-9467-43c1-8048-bc7864d30144
e3f23229-2258-41d2-b1a9-a9c4789fe958

Yes the players often see a pop-up/title that the phase has changed, although they are still in a phase, a video I submit later.

Kind regards

**Comment by tastybento** [comment]
This information helps. Thanks.

**Comment by tastybento** [comment]
I can't find anything in the code around block breaking that would cause this to happen. All the data structures are loaded correctly and programatic tests show that they output the correct phase for the block count number. So, my current theory is that the block count itself is changing somehow. If this happens again, I'd like the user to run the `/ob count` command to see what it says. Then share what phase they were on and then what it became. Is the count increasing or decreasing?
Other than that, I can only think that maybe some mod or admin is messing with the count using the admin setcount command! (Joke).

**Comment by Razorxd1993** [comment]
Hi, the /ob setcount command is not used in our system.
I copied all files to a test server and was able to replicate the problem directly in the "Berge" phase.
There appear from about 400-500 mined blocks snow blocks and powdersnow blocks, which are not entered in the phase, but appear one phase later in the "winter".

Hi, the /ob setcount command is not used in our system.
I copied all files to a test server and was able to replicate the problem directly in the Berge phase.
There appear from about 400-500 mined blocks snow blocks and powdersnow blocks, which are not entered in the phase, but appear one phase later in the "winter".

Also, the mobs of the next phase "Strays" spawn in the "Berge" phase.

![image](https://github.com/BentoBoxWorld/AOneBlock/assets/64865874/8964f5e9-28c9-4382-9837-6d8a202ab6cf)

**Comment by tastybento** [comment]
I was able to replicate the glow on two phases at the same time, and it was caused by a bug in the PanelItem class where the glow was not removed properly if you click different phases to jump to them. It does not actually indicate that 2 phases are active at the same time, it was just a bug where the glow was not removed. I've fixed it in the latest BentoBox, so thanks for finding that one!

For the snow blocks, I couldn't make any generate when I ran through the Berge phase. How did you get to that phases? Did you jump to it somehow? Were you breaking blocks in Creative mode?

I did see a number of calcite blocks, which are white - could those be them?
<img width="853" alt="Screenshot 2023-07-20 at 12 02 41 AM" src="https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/e162e13f-084a-4db8-9894-f897d9b0b0d0">

If you can replicate the snow, please do a screenshot of the F3 page showing the count if you can. Then maybe share the database and tell me the UUID of the player and I'll investigate more.

**Comment by tastybento** [comment]
This is totally weird. I can't replicate at all. Also, I am very surprised that you see two phases glowing in the GUI. Do you click on the phase icons to change phases at all?

I think the only way to see this is to try a copy of your server with the world. I thought about giving you a build with debugging on, but I can't think of what I would try to check for because I cannot see how this can be happening at all. I'm totally stumped, sorry.

**Comment by Razorxd1993** [comment]
Is it possible to contact you directly somehow? I don't want to upload my whole server publicly to GitHub.
Kind regards

**Comment by tastybento** [comment]
Yes, absolutely. Email is tastybento@bentobox.world.

**Comment by Razorxd1993** [comment]
Hi I have just sent you the EMail.

Kind regards :)

**Comment by tastybento** [comment]
Thanks for the files. When I start the server, I can see in the log that AOneBlock phases are loaded twice. When I removed all the plugins except for BentoBox they are only loaded once. I don't know yet which plugin is causing this, but this look suspicious. I am going to investigate further.

**Comment by tastybento** [comment]
Found it, it's ItemsAdder. I'm not sure if this is what is causing the issue, but it might be. I need to check into it. There was a PR that added support for it, so this may be the cause.

**Comment by tastybento** [comment]
I'm pretty sure I found the problem. I'll release a new version. Please try it and confirm it's fixed 🤞

**Comment by Razorxd1993** [comment]
Thank you for your efforts, I'll test it tomorrow directly :)

**Comment by tastybento** [comment]
Can you explain more what you mean about settings "excluded"?
