### ISSUE TITLE
Unexpected behavior with OneBlock Teams

### ISSUE THREAD

**Issue by mercurialmusic** [BentoBoxWorld/AOneBlock#339]
### Expected behavior

Based on settings, player balances, challenges, and inventories should be reset on team join.

Config section here (we don't allow echests because they derp most frequently with our MV Inventories and we have a creative world on the same server):

```
island:
[...]
    on-join:
      # What the addon should reset when the player joins or creates an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: true
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: true
      # Reset health - if true, the player's health will be reset.
      # Added since 1.8.0.
      health: true
      # Reset hunger - if true, the player's hunger will be reset.
      # Added since 1.8.0.
      hunger: true
      # Reset experience points - if true, the player's experience will be reset.
      # Added since 1.8.0.
      exp: true
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
    on-leave:
      # What the plugin should reset when the player leaves or is kicked from an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: true
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: true
      # Reset health - if true, the player's health will be reset.
      # Added since 1.8.0.
      health: true
      # Reset hunger - if true, the player's hunger will be reset.
      # Added since 1.8.0.
      hunger: true
      # Reset experience - if true, the player's experience will be reset.
      # Added since 1.8.0.
      exp: true
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
```

### Observed/Actual behavior

This is the first time I've had this one reported so may be a fluke, but reporting since I did eventually get an error out of it. Player 1 joined Player 2's team, Player 1's island was wiped as expected, but their balance, challenges, and inventory were left intact. We tested having them leave the team and go to their own new island, at which point everything was reset correctly, then I used admin commands to reinstate them on the team with fresh stats.

### Steps/models to reproduce

There was no error on the team join, but I did get an error when I had Player 1 leave the team, in case it's useful: https://gist.github.com/mercurialmusic/0524601d84b6874fc6eb542a54c0b284 

### BentoBox version

[05:07:21 INFO]: Running PAPER 1.20.1.
[05:07:21 INFO]: BentoBox version: 1.24.1
[05:07:21 INFO]: Database: JSON
[05:07:21 INFO]: Loaded Game Worlds:
[05:07:21 INFO]: acidisland_world (AcidIsland): Overworld, Nether, The End
[05:07:21 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[05:07:21 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[05:07:21 INFO]: Loaded Addons:
[05:07:21 INFO]: AcidIsland 1.18.1-SNAPSHOT-b995 (ENABLED)
[05:07:21 INFO]: AOneBlock 1.14.1 (ENABLED)
[05:07:21 INFO]: BSkyBlock 1.17.0-SNAPSHOT-b743 (ENABLED)
[05:07:21 INFO]: Challenges 1.3.0-SNAPSHOT-b531 (ENABLED)
[05:07:21 INFO]: DimensionalTrees 1.6.1-SNAPSHOT-b89 (ENABLED)
[05:07:21 INFO]: Greenhouses 1.7.4-SNAPSHOT-b359 (ENABLED)
[05:07:21 INFO]: Level 2.11.0-SNAPSHOT-b541 (ENABLED)
[05:07:21 INFO]: Limits 1.19.1-SNAPSHOT-b318 (ENABLED)
[05:07:21 INFO]: Warps 1.14.0-SNAPSHOT-b353 (ENABLED)

### Plugin list

Other relevant plugins include your super old mwmoney, which is still working great!

**Comment by tastybento** [comment]
The error is from Challenges and needs to be looked at. @BONNe FYI.
I'll try and test this and see if I can replicate it. If so, I'll move to the BentoBox project.
