### ISSUE TITLE
Placeholder: aoneblock_count and aoneblock_phase

### ISSUE THREAD

**Issue by Chew** [BentoBoxWorld/AOneBlock#35]
**Description**

I would like the following 2 placeholders added (if they have been added, I can't find them ;P

**Placeholder**: `aoneblock_count`

This would return the number of blocks you're on. 
"You are on block ___662___ in the Plains phase"

**Placeholder**: `aoneblock_phase`

This would return the phase you're on. 
"You are on block 662 in the ___Plains___ phase"

**Comment by tastybento** [comment]
Yes. https://bentobox-world.readthedocs.io/en/latest/gamemodes/AOneBlock/Placeholders/
