### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by themuffinthe** [BentoBoxWorld/AOneBlock#355]
### Is your feature request related to a problem?

I want to show **block mined**_(already existing %aoneblock_my_island_blocks_to_next_phase%
)_/blocks need to mine for each phase like _700_ for Plains and so....

### Describe the solution you'd like.

annd something like %aoneblock_my_island_blocks_for_phase%

### Describe alternatives you've considered.

I think this is the best way

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
This is done and will be in the next release, or on the CI server (ci.bentobox.world).

**Comment by themuffinthe** [comment]
its not working, its same as %aoneblock_my_island_blocks_to_next_phase%

**Comment by tastybento** [comment]
Really? I tested it, but I'll look at it again. Weird...

**Comment by tastybento** [comment]
I see the issue. Fixing...

**Comment by tastybento** [comment]
Okay, it should be fixed now.
