### ISSUE TITLE
Save Player on first join

### ISSUE THREAD

**Issue by Mithranduil** [BentoBoxWorld/AOneBlock#367]
### Is your feature request related to a problem?

player die if they join

### Describe the solution you'd like.

its however possible to deny the "fall" the first minute of the oneblock or something other?

cause currently player spawns, thinks the world is not loaded and just walk one block more, then they die in void ._.
(only when an player first joins the server, then its creates automatically an island)

### Describe alternatives you've considered.

set movement for player to 0 -> They could jump

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
Added a world setting option - use `/oba settings` - it's the bamboo block. Activate it. The time that the player cannot move is set in config.yml.
