### ISSUE TITLE
[New Feature] Next phase blocks needed placeholder

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#37]
#### Describe the solution you'd like us to implement.

Hi is it possible to implement something that allow players to know the amount of block break needed for the next phase?
We had this placheolder for now: {placeholderapi_aoneblock_my_island_count}
Is it possible to add:
{placeholderapi_aoneblock_my_island_nextphase_needed}?

This allow me to add something more in the scoreboard ;)

Thanks again

**Comment by tastybento** [comment]
Good idea.
