### ISSUE TITLE
Weather request AOneBlock

### ISSUE THREAD

**Issue by Paulibauli** [BentoBoxWorld/AOneBlock#370]
### Is your feature request related to a problem?

Hey, it would be nice to set weather and time individually 

### Describe the solution you'd like.

Is it Possible to implement to set the weather and time individually for each island on OneBlock?
Would be nice if it can be found in /ob setting.

### Describe alternatives you've considered.

At first everyone on the server was given the right to change the weather, but that didn't work quiet well. So it would be better to set the weather and time independently of others.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
All bentobox islands for the same gamemode are on the same world.
In Minecraft weather and time is global per world, so it is not possible to control it differently per player.
