### ISSUE TITLE
CRITICAL ERROR!* api.localization.BentoBoxLocale.getPrefixes

### ISSUE THREAD

**Issue by rodnicho** [BentoBoxWorld/AOneBlock#376]
### Expected behavior

a plugin that restarts normally following a reboot

### Observed/Actual behavior

[Server thread/INFO]: [BentoBox] Hooking with Vault...
[Server thread/INFO]: [BentoBox] Hooking with PlaceholderAPI...
[Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: bentobox [2.2.0]
[Server thread/INFO]: [BentoBox] Enabling game mode addons...
[Server thread/INFO]: [BentoBox] Enabling AOneBlock (1.15.0)...
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 4000_jungle.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 9500_desolation.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 0_plains_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 7500_the nether.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 3000_ocean_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 10500_deep_dark.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 0_plains.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Found firstBlock in fixedBlocks.
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 5000_swamp_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 12000_goto_0.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 11500_the end_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 2000_winter_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 10500_deep_dark_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 6000_dungeon_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 700_underground.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Found firstBlock in fixedBlocks.
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 8500_plenty.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 4000_jungle_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 7500_the nether_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 9500_desolation_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 8500_plenty_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 2000_winter.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 5000_swamp.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 11500_the end.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 3000_ocean.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 7000_desert.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 6000_dungeon.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 7000_desert_chests.yml
[Server thread/INFO]: [BentoBox] [AOneBlock] Loading 700_underground_chests.yml
[Server thread/INFO]: [BentoBox] Enabling other addons...
[Server thread/INFO]: [BentoBox] Enabling Level (2.12.0)...
[Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : caveblock-world
[Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : acidisland_world
[Server thread/INFO]: [BentoBox] [Level] Level hooking into AOneBlock
[Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: level [2.12.0]
[Server thread/INFO]: [BentoBox] [Level] Hooked into RoseStackers.
[Server thread/INFO]: [BentoBox] Enabling Chat (1.1.4)...
[Server thread/INFO]: [BentoBox] Enabling Likes (2.3.1)...
[Server thread/INFO]: [BentoBox] Loading likes...
[Server thread/INFO]: [BentoBox] Enabling Warps (1.14.0)...
[Server thread/INFO]: [BentoBox] [Warps] Loading warps...
[Server thread/INFO]: [BentoBox] Enabling Bank (1.7.1)...
[Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: bank [1.7.1]
[Server thread/INFO]: [BentoBox] [Bank] Hooking into AOneBlock
[Server thread/INFO]: [BentoBox] Enabling Biomes (2.1.1)...
[Server thread/INFO]: [BentoBox] Loading biomes...
[Server thread/INFO]: [BentoBox] Enabling Challenges (1.3.0)...
[Server thread/INFO]: [BentoBox] [Challenges] Loading challenges...
[Server thread/INFO]: [BentoBox] Enabling ControlPanel (1.13.1)...
[Server thread/INFO]: [BentoBox] Loading control panels...
[Server thread/INFO]: [BentoBox] Enabling MagicCobblestoneGenerator (2.5.1)...
[Server thread/INFO]: [BentoBox] [MagicCobblestoneGenerator] Loading generator tiers from database...
[Server thread/INFO]: [BentoBox] [MagicCobblestoneGenerator] Done
[Server thread/INFO]: [BentoBox] Enabling Visit (1.6.0)...
[Server thread/INFO]: [BentoBox] Addons successfully enabled.
[Server thread/INFO]: [BentoBox] Hooking with Multiverse-Core...
[Server thread/INFO]: Multiverse already knows about 'oneblock_world'!
[Server thread/INFO]: Success! Property generator was set to BentoBox
[Server thread/INFO]: Multiverse already knows about 'oneblock_world_nether'!
[Server thread/INFO]: Success! Property generator was set to null
[Server thread/INFO]: Multiverse already knows about 'oneblock_world_the_end'!
[Server thread/INFO]: Success! Property generator was set to null
[Server thread/ERROR]: [BentoBox] *****************CRITICAL ERROR!******************
[Server thread/ERROR]: [BentoBox] Cannot invoke "world.bentobox.bentobox.api.localization.BentoBoxLocale.getPrefixes()" because the return value of "java.util.Map.get(Object)" is null
[Server thread/ERROR]: [BentoBox]  Disabling BentoBox...
[Server thread/ERROR]: [BentoBox] *************************************************
[Server thread/INFO]: [BentoBox] Disabling addons...
[Server thread/INFO]: [BentoBox] Disabling Chat...
[Server thread/INFO]: [BentoBox] Disabling ControlPanel...
[Server thread/INFO]: [BentoBox] Addons successfully disabled.
[Server thread/INFO]: [BentoBox] Removing coops from islands...
[Server thread/INFO]: [BentoBox] Saving islands - this has to be done sync so it may take a while with a lot of islands...
[Server thread/INFO]: [BentoBox] Islands saved.
[Server thread/INFO]: [BentoBox] Closing database.
[Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "world.bentobox.bentobox.api.localization.BentoBoxLocale.getPrefixes()" because the return value of "java.util.Map.get(Object)" is null
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.managers.LocalesManager.getAvailablePrefixes(LocalesManager.java:155)
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.api.user.User.replacePrefixes(User.java:500)
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.api.user.User.translate(User.java:494)
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.api.user.User.getTranslation(User.java:458)
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.api.user.User.sendMessage(User.java:569)
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:256)
[Server thread/WARN]: 	at BentoBox-2.2.0.jar//world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:177)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1142)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)

### Steps/models to reproduce

I just restarted the server without touching anything

### BentoBox version

[16:11:20 INFO]: Running PAPER 1.20.4.
[16:11:20 INFO]: (git-Paper-454 (MC: 1.20.4))
[16:11:20 INFO]: BentoBox version: 2.2.0
[16:11:20 INFO]: Database: JSON
[16:11:20 INFO]: Loaded Game Worlds:
[16:11:20 INFO]: Loaded Addons:

### Other

[16:18:43 INFO]: This server is running Paper version git-Paper-454 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 99a6416)

**Comment by BONNe** [comment]
The locale you specified in bentobox config does not exist.

If you are not using `eng`, `zh` or `pt` you just need your country code: `de`, `lv` ... etc

**Comment by rodnicho** [comment]
I had restarted more than 20 times to configure the addons and plugins before this detail arrived, yet I set the language to French from the 2nd restart (after seeing that the plugin was installed correctly)

**Comment by rodnicho** [comment]
I just restarted the server after launching. The plugin works for now

**Comment by rodnicho** [comment]
THANKS

**Comment by rodnicho** [comment]
THANKS
