### ISSUE TITLE
Option to disable particles of oneblock

### ISSUE THREAD

**Issue by Mithranduil** [BentoBoxWorld/AOneBlock#377]
### Is your feature request related to a problem?

yea, performance issues of players with some lost hardware

### Describe the solution you'd like.

An Option in config of aoneblock to disable particles of the oneblock.
in the last Update every left click it spawns green particles

### Describe alternatives you've considered.

reduce amount and size in config, but its an very... messy way to prevent lags.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by mrfloris** [comment]
I don't want to disable it, i want to maybe move it to right click so they can "find" the magic block, but not get bothered by it? 
or maybe only for it for a little bit, but not 'forever'.

**Comment by Mithranduil** [comment]
> I don't want to disable it, i want to maybe move it to right click so they can "find" the magic block, but not get bothered by it? or maybe only for it for a little bit, but not 'forever'.

That's why there should be an option to disable it, people who would get it enabled, could let it enabled.

**Comment by mrfloris** [comment]
Sure, on top of fixing the underlying issue, rather than only having on/off

**Comment by tastybento** [comment]
There are some settings in the config to customize it right now. Note, these particles were always there, just smaller. I saw competitors who had fancier options so I wanted to stay competitive. You can tone them down how you like. However I can add some more settings to turn them off or make it only react to right click.

**Comment by mrfloris** [comment]
Yes, I personally love them, as do many players. But we do get some reports of 'this is a bit much' for left click, I'd defn. like to play around with the settings more and move it to right click.
