### ISSUE TITLE
Zombie head

### ISSUE THREAD

**Issue by pittaa** [BentoBoxWorld/AOneBlock#378]
### Expected behavior

When I kill 10 zombies with an enchanted creeper, it should drop 10 zombie heads. 

### Observed/Actual behavior

It dropped only one head. With different mobs, it works fine.

### Steps/models to reproduce

https://github.com/BentoBoxWorld/AOneBlock/assets/86187381/08821331-77b5-4c3e-a316-d15ff7d647e4

### BentoBox version

![image](https://github.com/BentoBoxWorld/AOneBlock/assets/86187381/5353c375-5643-41d7-8077-2ef4cce7c8f0)

**Comment by BONNe** [comment]
I do not think it is BentoBox issue.  We do not overwrite this behaviour to my knowledge.
