### ISSUE TITLE
A small option for editing where the items from the regenerating block in AOneBlock drop.

### ISSUE THREAD

**Issue by EnderBro123** [BentoBoxWorld/AOneBlock#38]
#### Is your feature request related to a problem?

Title says all.

#### Describe the solution you'd like us to implement.

Allow us to set where the dropped items from the broken AOneBlock block drop at.

#### Describe alternatives you've considered.

N/A?

### Additional context

None.

**Comment by EnderBro123** [comment]
Sorry lol

**Comment by maxlehot1234** [comment]
Why not make the magic bloc drops appear at the top of it like the original OneBlock map?

It would be MUCH BETTER than drop it in a random direction around it and make it drop in the void 85% of the time... Its not a hardcore oneblock plugin

**Comment by maxlehot1234** [comment]
Anything on this? This thing should be implemented or allow us with a true/false option or a "flag" per island to give the island owner the choice for this.

Thanks again

**Comment by tastybento** [comment]
I spent a while looking at this can I cannot actually see how to do it and keep all the handling of tools. I'm stuck. Does anyone have any ideas? @Poslovitch ?

**Comment by Poslovitch** [comment]
By using [`Block#getDrops(ItemStack)`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Block.html#getDrops-org.bukkit.inventory.ItemStack-) you might be able to get the actual drops... And maybe you could drop them on top of the block? Or at the player's feet?
