### ISSUE TITLE
Choose place for the starting hologram

### ISSUE THREAD

**Issue by Jimaie72** [BentoBoxWorld/AOneBlock#382]
### Is your feature request related to a problem?

Choose the location of the hologram at the start of the island
Currently, you cannot choose your location. It must be above the OneBlock

### Describe the solution you'd like.

Being able to choose a distance of the hologram from the OneBlock (x,y,z)

### Describe alternatives you've considered.

Choose the location of the hologram at the start of the island
> On config 

```
  # Display holograms
  holograms: true
  # Duration in seconds that phase holograms will exist after being displayed, if used.
  # If set to 0, then holograms will persist until cleared some other way.
  hologram-duration: 10
  # Duration in seconds that players cannot move when they start a new one block.
  # Used only if the Starting Safety world setting is active.
  starting-safety-duration: 10
```

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
I added it to config.yml:

```
  # Display holograms
  holograms: true
  # Hologram position - the offset to the magic block where holograms will appear
  hologram-offset: 0.5, 1.1, 0.5
```

The default is where it is now.

**Comment by Jimaie72** [comment]
Great, though, can you add a system so that the holo stays active even when the player starts to break their OneblocK?
The ideal would be a permission which would then allow the player to choose whether they want the holo to be visible or not

**Comment by tastybento** [comment]
That would be a different feature request so, please file that and I'll close this one.
