### ISSUE TITLE
Players coming from Parkour enter AOneBlock in Creative mode

### ISSUE THREAD

**Issue by ja2ui0** [BentoBoxWorld/AOneBlock#394]
### Expected behavior

When players leave Parkour and join AOneBlock via /ob, they are automatically set to the gamemode of the AOneBlock addon / world.

### Observed/Actual behavior

When players join Parkour, they are automatically set to Creative mode. When leaving for the AOneBlock island via /ob, they remain in Creative instead of being set back to Survival (or the set gamemode of AOneBlock). This does not happen with other island types. For example, leaving AOneBlock and entering Parkour sets Creative mode, but leaving Parkour for BSkyBlock, AcidIsland, or CaveBlock automatically resets gamemode to survival (the setting in those configs). Only AOneBlock seems to behave badly.

### Steps/models to reproduce

- Join the server and enter AOneBlock island with /ob. Note your gamemode, if default, is Survival.
- Join Parkour with /pk. Note that you are automatically set to creative.
- Rejoin AOneBlock with /ob. Note that you are still in creative.

### BentoBox version

Running PAPER 1.20.4.
(git-Paper-497 (MC: 1.20.4))
BentoBox version: 2.3.0
Database: JSON
Loaded Game Worlds:
acidisland_world (AcidIsland): Overworld, Nether, The End
boxed_world (Boxed): Overworld, Nether
bskyblock_world (BSkyBlock): Overworld, Nether, The End
caveblock-world (CaveBlock): Overworld, Nether, The End
oneblock_world (OneBlock): Overworld, Nether*, The End*
skygrid-world (SkyGrid): Overworld, Nether, The End
Loaded Addons:
AcidIsland 1.18.2 (ENABLED)
AOneBlock 1.16.0 (ENABLED)
Biomes 2.1.1 (ENABLED)
Border 4.3.0 (ENABLED)
Boxed 2.5.0 (ENABLED)
BSkyBlock 1.17.1 (ENABLED)
CaveBlock 1.18.0 (ENABLED)
Challenges 1.3.0 (ENABLED)
ControlPanel 1.13.1 (ENABLED)
InvSwitcher 1.12.0 (ENABLED)
SkyGrid 1.19.0 (ENABLED)
Warps 1.14.0 (ENABLED)

### Plugin list

Server Plugins (17):
Bukkit Plugins:
 - AngelChest, BentoBox, BentoBox-AcidIsland, BentoBox-AOneBlock, BentoBox-Biomes, BentoBox-Boxed, BentoBox-BSkyBlock, BentoBox-CaveBlock, BentoBox-Challenges, BentoBox-SkyGrid
 BentoBox-Warps, HiddenArmor, NoChatReports, ProtocolLib, ViaBackwards, ViaVersion, xaero-map-spigot

### Other

Note that I manually disabled (removed) Parkour 1.3.0 prior to making this report, so it doesn't show up in the "version" above.

**Comment by tastybento** [comment]
Hmm, I can't replicate this right now. The initial switching to a game mode is done by the game mode addon, e.g., Parkour, but the switching between game modes for worlds is done by the InvSwitcher addon. It should do it by default, but there is a config to not do it in the InvSwitcher config.yml:

```
options:
  # 
  # Per-world settings. Gamemode means Survivial, Creative, etc.
  inventory: true
  health: true
  food: true
  advancements: true
  gamemode: true
  experience: true
  ender-chest: true
  statistics: true
```
Is your gamemode option set to `false`? 

https://github.com/BentoBoxWorld/AOneBlock/assets/4407265/42cc6490-8487-4647-b3a9-20842cac96e1

**Comment by ja2ui0** [comment]
No, my InvSwitcher options are identical to yours. Any other thoughts?

**Comment by tastybento** [comment]
I can only think that InvSwitcher is remembering the last setting the player had so if they got it somehow and then teleported to another world then it would give it back to them when they teleport back. Have a look at the InvSwitcher database files (Store) for any affected players and see if their game mode is marked as Creative.

**Comment by ja2ui0** [comment]
I checked just now and every player in oneblock is set to SURVIVAL, but I have removed parkour and manually set everyone to survival since my report so that may not be particularly useful. When I get a chance to reinstall Parkour and test again with my own user against the InvSwitcher configs and db, I'll report back. Thanks for the input!
