### ISSUE TITLE
[BUG]  Ocean mob spawn with water arount it

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#40]
#### Describe the bug

Each time a ocean (fish, squid, etc) spawn, they spawn with water around it... Which is really bad and this should not happen. If there is no water, they should die instead (much better).
This also make the magic disappear sometimes...

#### Steps to reproduce the behavior

Play the Phase 3 (Ocean)

#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/5159244/80853668-78098580-8c00-11ea-88c5-cdd7ccadd97a.png)

##### BentoBox Version (Mandatory)

```
[17:14:32 INFO]: Running PAPER 1.15.2.
[17:14:32 INFO]: BentoBox version: 1.12.0
[17:14:32 INFO]: Database: JSON
[17:14:32 INFO]: Loaded Game Worlds:
[17:14:32 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[17:14:32 INFO]: Loaded Addons:
[17:14:32 INFO]: AOneBlock 1.1.5 (ENABLED)
[17:14:32 INFO]: Border 1.0.7 (ENABLED)
[17:14:32 INFO]: Challenges 0.8.1 (ENABLED)
[17:14:32 INFO]: Chat 1.0.5 (ENABLED)
[17:14:32 INFO]: Level 1.9.3 (ENABLED)
[17:14:32 INFO]: Limits 1.9.4 (ENABLED)
[17:14:32 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (25): AsyncWorldEdit, BentoBox, BlockVersion*, CMI, DeluxeChat, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, MultitoolPlusPro, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, NerfPhantoms, PlaceholderAPI, ProtocolLib, ProtocolSupport, SkinsRestorer, Vault, VKAutoPickup, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard
```
 

Thanks again for discovering few bugs ;)

**Comment by tastybento** [comment]
No, this isn't a bug. It is by design.

**Comment by maxlehot1234** [comment]
Well its sad :(

Can you implement a true/false option for this design thing?
Since the water stay there. At least make the water disappear when the mob go away?

**Comment by maxlehot1234** [comment]
@tastybento I understand the design thing but why the turtle spawn without water?

**Comment by tastybento** [comment]
Only animals that need water to live have the water.

**Comment by maxlehot1234** [comment]
Dis you realize that it add a lot of difficulty to mine blocks when the water was put around the magic block?
I am pretty sure that a true/false thing can be done and that a lot of server owner will remove that effect.

It also remove the ability to players to catch a rich when they spawn using their bucket water... It's sad.

It's just my opinion. I ask my dev to do it since you don't want too :( 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tastybento** [comment]
A Pull Request with this as an option would be very welcome!
