### ISSUE TITLE
[BUG] Any water plant that spawn, make magic block to disappear

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#41]
#### Describe the bug

Any water plant that spawn, make magic block to disappear

#### Steps to reproduce the behavior

Reach phase 3 and wait until a coral plant spawn. Break it and magic block will not reappear

#### Expected behavior

The magic block should reappear after that

##### BentoBox Version (Mandatory)

```
[17:14:32 INFO]: Running PAPER 1.15.2.
[17:14:32 INFO]: BentoBox version: 1.12.0
[17:14:32 INFO]: Database: JSON
[17:14:32 INFO]: Loaded Game Worlds:
[17:14:32 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[17:14:32 INFO]: Loaded Addons:
[17:14:32 INFO]: AOneBlock 1.1.5 (ENABLED)
[17:14:32 INFO]: Border 1.0.7 (ENABLED)
[17:14:32 INFO]: Challenges 0.8.1 (ENABLED)
[17:14:32 INFO]: Chat 1.0.5 (ENABLED)
[17:14:32 INFO]: Level 1.9.3 (ENABLED)
[17:14:32 INFO]: Limits 1.9.4 (ENABLED)
[17:14:32 INFO]: Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (25): AsyncWorldEdit, BentoBox, BlockVersion*, CMI, DeluxeChat, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, MultitoolPlusPro, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, NerfPhantoms, PlaceholderAPI, ProtocolLib, ProtocolSupport, SkinsRestorer, Vault, VKAutoPickup, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard

```
 
Not sure if its related to any other plugin ( I doubt )

Thanks again.

**Comment by maxlehot1234** [comment]
In fact all of these "blocks" cause the magic to disappear:

DEAD_FIRE_CORAL_FAN
DEAD_TUBE_CORAL
DEAD_TUBE_CORAL_FAN
DEAD_HORN_CORAL_FAN
DEAD_HORN_CORAL
DEAD_BUBBLE_CORAL
DEAD_BUBBLE_CORAL_FAN
DEAD_BRAIN_CORAL
DEAD_BRAIN_CORAL_FAN

I remove them from the config and problem solved. But if you can do something ;) It would be great

**Comment by tastybento** [comment]
Really? If I get one of those I can just hit it and it'll move on. See the video:
[Screen Recording 2020-05-01 at 10.07.28 PM.mov.zip](https://github.com/BentoBoxWorld/AOneBlock/files/4567121/Screen.Recording.2020-05-01.at.10.07.28.PM.mov.zip)

**Comment by maxlehot1234** [comment]
I will test it again without any plugins to see if it's the same issue and I let you know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maxlehot1234** [comment]
> Really? If I get one of those I can just hit it and it'll move on. See the video:
> [Screen Recording 2020-05-01 at 10.07.28 PM.mov.zip](https://github.com/BentoBoxWorld/AOneBlock/files/4567121/Screen.Recording.2020-05-01.at.10.07.28.PM.mov.zip)
I update one of the plugin and it work, BUT, do you know why the drip nothing when we break them?

I trywithout any plugin and they drop nothing. It simply break and a new block spawn without giving anything.

Is that normal?

**Comment by tastybento** [comment]
Yes, that's normal, if you don't use silk touch.
