### ISSUE TITLE
Downloaded bank but not showing

### ISSUE THREAD

**Issue by JamesWongGames** [BentoBoxWorld/AOneBlock#413]
### Expected behavior

Bank

### Observed/Actual behavior

Nothing

### Steps/models to reproduce

/ob bank = nothing

### BentoBox version

2.7.0

### Plugin list

![image](https://github.com/user-attachments/assets/f3e5f4f3-384c-461c-a0b1-4062a4b9146f)

### Other

I want to be able to use bank

**Comment by tastybento** [comment]
You will need Vault to enable it.
https://www.spigotmc.org/resources/vault.34315/

If you still have an issue, share the output of `/bbox v`

**Comment by JamesWongGames** [comment]
alr thanks
