### ISSUE TITLE
[Question] How I can make this mob to spawn? mooshroom

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#42]
Hi,

I just want to know how I can make this mob to spawn. 
https://minecraft.gamepedia.com/Mooshroom

Its a really useful mob for mushroom soup.

Thanks again if anyone had the answer.

**Comment by tastybento** [comment]
This should work: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html#MUSHROOM_COW
