### ISSUE TITLE
Phase list command

### ISSUE THREAD

**Issue by bonjourkemal** [BentoBoxWorld/AOneBlock#45]
We need an information command that shows which biome it gets when it breaks how many blocks.

**Comment by tastybento** [comment]
There is an `/ob count` command that will show you how many blocks you have broken and what phase you are in. Does this give you what you want?

**Comment by bonjourkemal** [comment]
No, it's actually a list of all the phases shows how many blocks we should break. Can I explain? So like command /ob phaselist

**Comment by bonjourkemal** [comment]
/ob count command only shows its current status.

**Comment by tastybento** [comment]
Okay! I will put it behind a permission though, because some may want that information to be secret.

**Comment by maxlehot1234** [comment]
> We need an information command that shows which biome it gets when it breaks how many blocks.

You can create this using a GUI plugin, custom command plugin, etc.

But having it in the config with a true/false option can do the trick too
Thanks for that suggestion. I love it :)

**Comment by maxlehot1234** [comment]
This ticket can be closed I think ;)
