### ISSUE TITLE
Bug occurs when creating island

### ISSUE THREAD

**Issue by W1nterkaust** [BentoBoxWorld/AOneBlock#46]
#### Describe the bug

When using the command /ob, it warps you to a new instance mid air, then sends you back to your original world (Two worlds setup for this) with the message "could not find a safe spot to teleport you to on the island" 

#### Steps to reproduce the behavior

Typing in the command /ob and waiting for your island to be generated. 

#### Expected behavior

Command should produce an island for the player instead of nothing and warping you back to the original world. 
#### Screenshots and videos (Optional)

https://prnt.sc/sb0515 
##### BentoBox Version (Mandatory)

```
Running Paper 1.15.2
BentoBox version: 1.13.1
Database: JSON
Loaded Game Worlds: 
oneblock_world (OneBlock): Overworld, Nether*
Loaded Addons: 
AOneBlock 1.17 (Enabled)
Border 1.0.7 (Disabled)
Challenges 0.8.2 (Enabled)
Chat 1.1.0-SNAPSHOT-b26 (Enabled)
Level 2.0.0-SNAPSHOT-b354 (Enabled)
Likes 2.0.0-SNAPSHOT-b24 (Enabled)
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

I run one additional survival world.

**Comment by tastybento** [comment]
I downloaded AOneBlock and BentoBox from download.bentobox.world and did `/ob` and it all worked, so I can't replicate this. Did you change any of the configs? How did you do the install?

```
> bbox v
[11:51:37 INFO]: Running PAPER 1.15.2.
[11:51:37 INFO]: BentoBox version: 1.13.1
[11:51:37 INFO]: Database: JSON
[11:51:37 INFO]: Loaded Game Worlds:
[11:51:37 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[11:51:37 INFO]: Loaded Addons:
[11:51:37 INFO]: AOneBlock 1.1.7 (ENABLED)
[11:51:37 INFO]: Chat 1.0.5 (ENABLED)
[11:51:37 INFO]: Likes 1.7.1 (ENABLED)
[11:51:37 INFO]: Warps 1.9.3 (ENABLED)
```

**Comment by W1nterkaust** [comment]
I changed nothing the configs, I followed the instructions from the github page for oneblock for installation: 

- Installed BentonBox & let it run on the server to create files 
- Placed the Aoneblock jar in the addon folder
- Restarted the server
- Had BentoBox create the oneblock_world & oneblock_nether folders, running alongside my survival_world, survivall_nether and survival_end worlds 
- opened the config file to look at it, but didn't edit anything
- went on my server, typed /ob and it generated a new island 
- broke like two blocks in survival before the island stopped generating blocks and kicked me back to my survival world 
- Tried the /ob command again, it comes up with an error "could not find a safe spot to teleport you to on the island"

**Comment by tastybento** [comment]
> * broke like two blocks in survival before the island stopped generating blocks and kicked me back to my survival world

There is nothing in AOneBlock or BentoBox that would kick you back to your survival world. What other plugins do you have running? Do you have any anti-cheat plugins?

**Comment by maxlehot1234** [comment]
It happen to me sometimes too. No idea how to replicate this, since it works 99% of the time for me and sometimes I am not able to join the island anymore.
I need to reset it and when I do ./ob same issue occured again.
When this occured, I need to clear the Database folder into BentoBox plugin folder to fix the issue.

I can try to replicate it. It also happen sometimes when I create a new blueprint. The blueprint works great without any issue, but it prevent me to join the oneblock thing cause the telport don't work


Sorry if its not clear.
I can open a new issue for this, but it will be the same things as this ticket.

**Comment by tastybento** [comment]
@maxlehot1234 Are you sure this is the same? @W1nterkaust says that the blocks are there, but when he breaks them he is teleported back to another world. That is definitely not BentoBox or AOneBlock doing that. Is that what you see? If so, what plugins do you use? Maybe there is a common anti-cheat plugin triggering.

**Comment by maxlehot1234** [comment]
Not the really same issue, but i already got this message:L
![image](https://user-images.githubusercontent.com/5159244/81448230-0c697000-914c-11ea-9f8e-7f6ddc0cccf8.png)

I don't use anticheat for now. Need to find a way to implement all features I want and make my dev fix issues/bugs you wont fix for multiple reasons (I understand why, don't worry).


I will try to replicate the teleport issue error on my side and open a ticket. Maybe it will be something similar on my side too.

**Comment by kFxDaKing** [comment]
Same problem

**Comment by timbo2040** [comment]
I have this issue too, only have BentoBox, BentoBox-AOneBlock, BentoBox-Bank, BentoBox-Biomes, BentoBox-Challenges, BentoBox-CheckMeOut, BentoBox-Level, BentoBox-Visit, BentoBox-Warps, floodgate

**Comment by timbo2040** [comment]
Continues to happen after complete reinstall. Worked previously on test server and nothing has been changed since.

**Comment by tastybento** [comment]
Can you open a new ticket and fill in the details for it please?
