### ISSUE TITLE
aoneblock range permisson not working

### ISSUE THREAD

**Issue by minhthanh920** [BentoBoxWorld/AOneBlock#47]
### Description
My config:
  distance-between-islands: 200
  protection-range: 50
then i set permisson
aoneblock.island.range.150
but island not bigger.

##### BentoBox Version (Mandatory)
bentobox : 1.13.1
Aoneblock : 1.1.7
paper : 1.15.2

**Comment by tastybento** [comment]
Did you log out and back in? Permissions are checked when you log in and set the island range.

**Comment by maxlehot1234** [comment]
@tastybento @minhthanh920 Just test it on my side and it works perfectly after I logout and login again and players got a message in the chat related to this. But it will be great to display a chat message that told the player to logout and login to get this thing take effect.

**Comment by tastybento** [comment]
There's no permission change event to track, so that's why you have to relog and that's also why we can't show a message. You could do it when you give them the permission as an extra command though, e.g. via a shop or something, but that's  out of my scope.
