### ISSUE TITLE
Broadcast when a player completes a phase.

### ISSUE THREAD

**Issue by nolky** [BentoBoxWorld/AOneBlock#49]
#### Describe the solution you'd like us to implement.

Similar to the Challenges addon, I want it to be able to broadcast in chat for when a player moves onto the next phase or completes all phases and returns to the beginning. That's it, thanks!

**Comment by maxlehot1234** [comment]
#33 
I suggest a command after each phase, so this will allow you to use commands feature between phase, but no idea why this thing will be implemented.

**Comment by nolky** [comment]
That seems interesting! Would be very useful for a system I want to add in the future, thanks for sharing that!

**Comment by tastybento** [comment]
I'll focus on #33.
