### ISSUE TITLE
You do not have the required trail to interact with cobblestone ?

### ISSUE THREAD

**Issue by gnydnzeki** [BentoBoxWorld/AOneBlock#67]
When I set up the server with Bentobox one block plugin, I get the only plugin essentials and the error in the picture constantly. Language is Turkish but I would be glad if you can help.
![a](https://user-images.githubusercontent.com/65101203/81881719-8f018d80-9599-11ea-8718-3346a4ea991e.png)

**Comment by maxlehot1234** [comment]
> When I set up the server with Bentobox one block plugin, I get the only plugin essentials and the error in the picture constantly. Language is Turkish but I would be glad if you can help.
> ![a](https://user-images.githubusercontent.com/65101203/81881719-8f018d80-9599-11ea-8718-3346a4ea991e.png)

Did you try to break it using a pickaxe? Just to see if it works?

Please follow the bug issue guidelines if you want more help. Its hard to help without more informations

**Comment by gnydnzeki** [comment]
Look, I tried everything, but I just don't get this error when I give myself op authority. I only get it in case of player please help.

**Comment by maxlehot1234** [comment]
What is your paper version, bentobox version, aoneblock version, java version, did you test it on a localhost server? Essentials or EssentialsX, latest essentialsX version from their jenkins or not?

Help us a little bit more please.

**Comment by gnydnzeki** [comment]
I am not using paper. Spigot, essentialsx and bentobox one block plug-in is the latest version.

**Comment by maxlehot1234** [comment]
Spigot 1.8, 1.9, .1.12, 1.14, 1.15? Please do ./version and give us the result
Do ./pl  too
Do ./bentobox version and put the results here

Im a not supposed to help, but I will do my best but without anything, even the devs will not able to help you, so help me a little with your server version, plugins versions, etc..... Or wait a dev if you are not able to provide these informations.

Also, if you test on a localhost server Without being OP, do you have the same issue?

**Comment by gnydnzeki** [comment]
Can I reach you via discord? Add me plz benres#9228

**Comment by tastybento** [comment]
This error is coming from Essentials AntiBuild and not BentoBox or AOneBlock. Check here: http://wiki.ess3.net/wiki/AntiBuild#Permission_control
If you are going to use that plugin, make sure your players have the `essentials.build` permission.
