### ISSUE TITLE
3 bugs on AOneBlock

### ISSUE THREAD

**Issue by immakita** [BentoBoxWorld/AOneBlock#72]
Hi. I am using last SNAPSHOT B-88. I've a problem with AOneBlock.
When i delete an island with the command "obadmin delete <player>", 
First: The island removing too slow
Second: we are falling down while removing our islands. So we don't teleporting spawn.
Third and last: after our island deleted, we usually trying to open new island. But we are seeing new error Like "There is no safe area on your island"

I didn't change anything at /AOneBlock/config.yml

**Comment by tastybento** [comment]
First, it's dangerous to use the snapshot builds - they may be unstable, so use the release builds.
Second, please fill in the bug template. e.g., share your `bbox version` output from the console so I know what you are running.
Third, what machine are you using to run your Minecraft server and how much memory does the JVM have?
Finally, are you setting up this server? It may be best to reset everything and start from a clean install.

**Comment by immakita** [comment]
i am using BentoBox 1.13.0
And I've same problem with 1.1.7 AOneBlock
Server is running with 14GB Memory
I'am using Windows server 2012
I cleared all data on BBox and AOneBlock. But problem didn't change

**Comment by tastybento** [comment]
Do you know how to use timings? See https://www.spigotmc.org/wiki/timings/

While you are taking timings, do the things that lag. Then paste the timings URL and share it with me.

Also, run the command `bbox version` in the console and copy and paste the result.

By the way, what language do you speak?

**Comment by immakita** [comment]
I am speaking Turkish

 https://timings.aikar.co/?id=8f67b3f033b14
f45ab4fc7953f7da6be

INFO]: Sunucu PAPER 1.15.2 sürümünde çalışıyor.
INFO]: BentoBox sürümü: 1.13.1
INFO]: Database: JSON
INFO]: Yüklenen oyun dünyaları:
INFO]: oneblock (OneBlock): Overworld
INFO]: Yüklenen eklentiler:
INFO]: AOneBlock 1.2.0-SNAPSHOT-b88
INFO]: Challenges 0.8.2
INFO]: Chat 1.0.5
INFO]: Likes 1.7.1
INFO]: Warps 1.9.3

**Comment by tastybento** [comment]
I don't see anything particularly wrong in the timings. The deletion task does take a long time to run but it should not cause lag. You can try and set the deletion speed in BentoBox's config.yml to 0 and that will not delete islands and see if that helps.

Also, you should run your server using the latest start tags as Paper recommends. See https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
```
java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paperclip.jar nogui
```

**Comment by immakita** [comment]
I didn't say AOneBlock cousing lag

I said that;
when I delete an island, players on the island cannot teleport. In other words, the players on the island fall into space and die.

It also gives the player who wants to re-create the island, "No safe area found on your island" error

**Comment by immakita** [comment]
without forgetting, Aikar's Flags cause high CPU usage. I don't know if it's the problem.

**Comment by tastybento** [comment]
Sorry, I misunderstood. If you delete the island with the admin command `/oba delete` then yes, if players are on the island then they will fall and die. But that command is an admin command for emergency island cleaning or maintenance and not for normal game play. If a player wants to restart their island then they run the `/ob reset` command. Then they will be teleported to their new OneBlock. 
Does that help?

**Comment by immakita** [comment]
Yeah but you can change delete event like ASkyBlock islan delete event. On ASkyBlock. When we delete an island using /asadmin delete, the player on the island teleporting spawn area

**Comment by immakita** [comment]
But Thanks for your help :)

**Comment by tastybento** [comment]
Okay gotcha. Understood. I’ll look into it.

**Comment by immakita** [comment]
Last thing, Why are our items not cleaned when we die on our island?

Keepinventory false on oneblock world

**Comment by tastybento** [comment]
Like you say, that’s a game rule so if you are setting keepInventory false and it’s not working then I don’t know. AOneBlock does not manage your inventory when you die. It only has settings for new islands, resets and joining or leaving an island team.
