### ISSUE TITLE
chests saving as empty/filled with air

### ISSUE THREAD

**Issue by kMagic142** [BentoBoxWorld/AOneBlock#75]
#### Describe the bug

Chests are saving filled with AIR in oneblocks.yml.
#### Steps to reproduce the behavior

It happened twice to me. First time I wasted 2 hours filling chests and setting them to be as I wanted, and at the end I checked the oneblocks.yml file and all the chests we're filled with AIR instead of the items I had in the chests. This time, happened exactly the same, but the weird thing about it is that SOME chests don't save filled with air, except, they are exactly as I saved them.
#### Expected behavior

I don't exactly know, but the thing I know is that this should not happen. 
##### BentoBox Version (Mandatory)

```
[12:50:40 INFO]: Running Invalid 1.15.2.
[12:50:40 INFO]: BentoBox version: 1.13.1
[12:50:40 INFO]: Database: JSON
[12:50:40 INFO]: Loaded Game Worlds:
[12:50:40 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[12:50:40 INFO]: Loaded Addons:
[12:50:40 INFO]: AOneBlock 1.2.0 (ENABLED)
[12:50:40 INFO]: BentoBox-InvSwitcher 1.6.1 (ENABLED)
[12:50:40 INFO]: Biomes 1.7.0 (ENABLED)
[12:50:40 INFO]: Border 1.0.7 (DISABLED)
[12:50:40 INFO]: Challenges 0.8.2 (ENABLED)
[12:50:40 INFO]: Chat 1.0.5 (ENABLED)
[12:50:40 INFO]: ControlPanel 1.7.0 (ENABLED)
[12:50:40 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[12:50:40 INFO]: IslandFly 1.7.3 (ENABLED)
[12:50:40 INFO]: Level 2.0.0 (ENABLED)
[12:50:40 INFO]: Limits 1.12.2 (ENABLED)
[12:50:40 INFO]: MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
[12:50:40 INFO]: Warps 1.9.3 (ENABLED)


```

#### Plugins (Optional)

```
[16:36:03 INFO]: Plugins (51): AdvancedOreGen, AntiDisconnectSpam, BCommons*, BentoBox, BlockParticles, Citizens, CitizensCMD, ClearLag, CombatLogX, ConsoleSpamFix, Core*, CrazyAuctions, CrazyCrates, CustomSkinsManager, DeluxeChat, DeluxeMenus, Essentials, EssentialsSpawn, FeatherBoard*, FiguresFix*, GAListener*, HideAchievements*, HideStream*, HolographicDisplays, IPWhitelist*, JoinItems115*, JumpPads, LagAssist, LeaderHeadsRevamped, LiteBans, LuckPerms, MineableSpawners, MobFarmManager, Multiverse-Core*, MVdWPlaceholderAPI*, MyCommand, PlaceholderAPI, ProtocolLib, ShopGUIPlus, TAB, TimedRewards*, TpLogin*, TradeMe, TreysCommandBlocker*, UPotions, Vault, VoteParty, Votifier, WorldEdit, WorldGuard, YourLilMagicItems*

```
 
### Additional context (Optional)

I closed this issue yesterday because I thought the problem was from me not updating the addon. Turns out that I was wrong, and the issue still occurs, but not frequently. It seems that most of the chest that I set in game are saved as they were, but some of them save filled with air. I don't know what would be the cause of this problem, but I'm open to help with finding out and solving it.

**Comment by tastybento** [comment]
Can you give me some steps that you are using? Like what you filled the chests with and what commands you used? Any ideas about the items in the chests? Unusual ones? How about the chest types? Epic, etc?

**Comment by kMagic142** [comment]
> Can you give me some steps that you are using? Like what you filled the chests with and what commands you used? Any ideas about the items in the chests? Unusual ones? How about the chest types? Epic, etc?

The command I used is /oba (or isa as I set it in the config) setchest PLAINS Common
I didn't use any special items, just some flowers, saplings, seeds, flower pots and nothing too special, just vanilla minecraft things to match the theme of the phase. As when it comes to rarity, I noticed that mostly the COMMON and UNCOMMON types are saving as AIR. Also, there are some items that save normally along them, like dandelion and poppy.

**Comment by tastybento** [comment]
When you run that command, can you confirm that you are looking at the chest that you want to save?

**Comment by kMagic142** [comment]
> When you run that command, can you confirm that you are looking at the chest that you want to save?

Yes. I am looking at a chest while running that command.

**Comment by tastybento** [comment]
I'm having trouble replicating this right now. Can you share the .yml file that shows the chests? If you can find a specific item that causes the problem, that'd be useful too.

**Comment by kMagic142** [comment]
> I'm having trouble replicating this right now. Can you share the .yml file that shows the chests? If you can find a specific item that causes the problem, that'd be useful too.

Sorry for the late response, I've been busy with work for the past day.
Here are the contents of the .yml file:

`'0':
  chests:
    '1':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: OXEYE_DAISY
        3:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AZURE_BLUET
        5:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AZURE_BLUET
        7:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PINK_TULIP
        8:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: DANDELION
        9:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AZURE_BLUET
        10:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PINK_TULIP
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: DANDELION
        16:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PINK_TULIP
        18:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: DANDELION
        20:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PUMPKIN_SEEDS
        21:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: OXEYE_DAISY
        23:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PUMPKIN_SEEDS
        25:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: OXEYE_DAISY
      rarity: COMMON
    '2':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        2:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        4:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        20:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        6:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        23:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        8:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        9:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        25:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        12:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
      rarity: COMMON
    '3':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        1:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        2:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        3:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        6:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        7:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        10:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        11:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        14:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        15:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        16:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        19:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        21:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        24:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        26:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
      rarity: UNCOMMON
    '4':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        1:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        2:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        3:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        6:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        7:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        10:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        11:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        14:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        15:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        16:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        19:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        21:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        24:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        26:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
      rarity: UNCOMMON
    '5':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        1:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        2:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        4:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        6:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        7:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        10:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        15:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        16:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        19:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        20:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        21:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        24:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        26:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
      rarity: UNCOMMON
    '6':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        1:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        2:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        3:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        7:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        8:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_TULIP
        10:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        14:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_TULIP
        15:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        16:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        19:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        20:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        21:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        23:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AIR
          amount: 0
        25:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_TULIP
        26:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
      rarity: UNCOMMON
    '7':
      contents:
        0:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        1:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        2:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        4:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PINK_TULIP
        6:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: WHITE_TULIP
        7:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_DYE
        8:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_TULIP
        9:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: AZURE_BLUET
        10:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: YELLOW_DYE
        12:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PINK_TULIP
        13:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: MUSIC_DISC_13
        14:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_TULIP
        15:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
        17:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: PINK_TULIP
        18:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: WHITE_TULIP
        19:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: ORANGE_TULIP
        20:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: WHITE_TULIP
        21:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: DANDELION
        23:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: OXEYE_DAISY
        25:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: RED_TULIP
        26:
          ==: org.bukkit.inventory.ItemStack
          v: 2230
          type: SUNFLOWER
      rarity: RARE
`

Also, I'll try to find a specific item and reply when I'm done.

**Comment by tastybento** [comment]
That's a good clue. The item stacks a literally AIR. Huh. What server are you using specifically? i.e., where did you get it from or did you build it?

**Comment by kMagic142** [comment]
> That's a good clue. The item stacks are literally AIR. Huh. What server are you using specifically? i.e., where did you get it from or did you build it?

The server I'm using is built by me, with some custom plugins. The spigot I'm using is 1.15.2 Tuinity, which is a fork of Paper.

I checked if these plugins are somehow interfering with BentoBox or could be a cause to the items saving as AIR, but the results where negative. No other plugins that are on that server are connected to this problem.

I also tried on a local server with the same spigot version, with only necessary plugins, and this problem appeared again.

I think it might be a problem with 1.15.2 Tuinity, but I want you to confirm that to be sure.

**Comment by tastybento** [comment]
Please try Build 96 or later: https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/

See if you can still replicate the issue.

**Comment by kMagic142** [comment]
> Please try Build 96 or later: https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/
> 
> See if you can still replicate the issue.

So I tried this version just now. It seems that I can only run the command when looking at a fully filled chest, but if there is even one item missing from the chest being filled, it won't let me. This is the error:

`[22:40:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'isa setchest Plains COMMON' in world.bentobox.aoneblock.commands.AdminCommand(isadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1853) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1661) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1151) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1144) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1120) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:963) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
        at world.bentobox.aoneblock.commands.AdminSetChestCommand.execute(AdminSetChestCommand.java:93) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Tuinity-"55e85bb"]
        ... 16 more
`

**Comment by tastybento** [comment]
Okay, fixed. Please try the latest build.

**Comment by kMagic142** [comment]
> Okay, fixed. Please try the latest build.

Seems like the problem is solved. Thank you!
