### ISSUE TITLE
[Feature Request] Users can select their phase after completion of all phases.

### ISSUE THREAD

**Issue by kaaaaaale** [BentoBoxWorld/AOneBlock#76]
### Description
I want users that have completed all phases defined in oneblocks.yml to have the ability to choose their phase at will, this can be toggleable in the config. They can either choose it through a command such as ``/ob phase {phase}`` or a GUI. If the user hasn't completed all phases it will return ``"Complete all phases to return to past phases!"``.

### Describe alternatives you've considered.
Create a DeluxeMenus GUI that is only accessible with a permission that can somehow be given at the completion of the last phase, in here there will be items that when clicked on will set the user's block count to the minimum to be in that phase using a console command to run ``/oba setcount {player} {number}``.

**Comment by maxlehot1234** [comment]
+1
