### ISSUE TITLE
[Bug] drop-on-top doesn't seems to work properly.

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#77]
#### Describe the bug

Hi, I just test the latest dev version from jenkins, but blocks don't drop at the top of the magic block.
It drop on the block near the magicblock.

I try to put: drop-on-top: true or try false too, but got the same problem even after a server restart.

#### Steps to reproduce the behavior

Install latest dev build of bentobox and aoneblock and test.

#### Expected behavior

Blocks should drop at the top of the magic block which is not the case right now

#### Screenshots and videos (Optional)

N/A

##### BentoBox Version (Mandatory)

```
>....[09:07:09 INFO]: Running PAPER 1.15.2.
>.... [09:07:09 INFO]: BentoBox version: 1.14.0-SNAPSHOT-b1800
>.... [09:07:09 INFO]: Database: JSON
>.... [09:07:09 INFO]: Loaded Game Worlds:
>.... [09:07:09 INFO]: oneblock_world (OneBlock): Overworld, Nether*
>.... [09:07:09 INFO]: Loaded Addons:
>.... [09:07:09 INFO]: AOneBlock 1.3.0-SNAPSHOT-b98 (ENABLED)
>.... [09:07:09 INFO]: Border 1.0.7 (ENABLED)
>.... [09:07:09 INFO]: ControlPanel 1.12.0-SNAPSHOT-b11 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (32): BentoBox, BlockVersion*, BossShopPro, BuycraftX, CMI, CMIPaperLib, ConsoleSpamFix, DeluxeChat, EasyWhitelist*, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, NerfPhantoms, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, ServerBooster, SkinsRestorer, TreeAssist, UltraCustomizer, Vault, VKAutoPickup, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard
```
 
Thanks again and have a nice day/night

**Comment by tastybento** [comment]
It is dropped on top of the block, but it has some velocity so it can move a bit. This change will reduce the velocity to zero.
