### ISSUE TITLE
[MAJOR issue] Latest dev version stop counting block breaks

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#78]
#### Describe the bug

Latest dev build: AOneBlock-1.3.0-SNAPSHOT-b98 stop counting block break.
https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/98/

#### Steps to reproduce the behavior

Install latest bentobox and latest aoneblock dev build versions and break the magic block, counter stop counting blocks. The placeholder (  %aoneblock_my_island_count%  ) seems to stop counting infact. It display the latest value from file and not update.

#### Expected behavior

Block count placeholder: %aoneblock_my_island_count% should return the block break value.

#### Screenshots and videos (Optional)

N/A

##### BentoBox Version (Mandatory)

```
[09:20:07 INFO]: Running PAPER 1.15.2.
>.... [09:20:07 INFO]: BentoBox version: 1.14.0-SNAPSHOT-b1792
>.... [09:20:07 INFO]: Database: JSON
>.... [09:20:07 INFO]: Loaded Game Worlds:
>.... [09:20:07 INFO]: oneblock_world (OneBlock): Overworld, Nether*
>.... [09:20:07 INFO]: Loaded Addons:
>.... [09:20:07 INFO]: AOneBlock 1.2.2-SNAPSHOT-b96 (ENABLED)
>.... [09:20:07 INFO]: Border 1.0.7 (ENABLED)
>.... [09:20:07 INFO]: ControlPanel 1.12.0-SNAPSHOT-b11 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (32): BentoBox, BlockVersion*, BossShopPro, BuycraftX, CMI, CMIPaperLib, ConsoleSpamFix, DeluxeChat, EasyWhitelist*, Essentials, EssentialsSpawn, FeatherBoard*, LuckPerms, LuckPermsCompat*, Multiverse-Core, Multiverse-Inventories, MVdWPlaceholderAPI*, NerfPhantoms, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, ServerBooster, SkinsRestorer, TreeAssist, UltraCustomizer, Vault, VKAutoPickup, VoidGenerator, WorldBorderAPI*, WorldEdit, WorldGuard
```
 
Thanks again if you can fix this in a new dev build :)

**Comment by tastybento** [comment]
I cannot replicate with with the latest build (100).

```
> papi parse tastybento %aoneblock_my_island_count%
[15:37:53 INFO]: 38
[15:38:09 INFO]: []<tastybento> breaking blocks
> papi parse tastybento %aoneblock_my_island_count%
[15:38:18 INFO]: 41
> 
```

**Comment by maxlehot1234** [comment]
@tastybento Problem solved with build 100 :)
I will close this issue than ;)
