### ISSUE TITLE
Ability to softlock your magic block.

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/AOneBlock#79]
#### Describe the bug

Softlock your self on AOneBlock. Get a leaf block and wait for it to despawn. there wont be a magic block left just a hole.

#### Steps to reproduce the behavior

1.) Get a leaf block from the magic block.
2.) Wait for it to despawn.

#### Expected behavior

Leafs generated from the magic block wont despawn.

#### Screenshots and videos (Optional)

N/A

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.12.0
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether*
Loaded Addons:
AOneBlock 1.1.2 (ENABLED)
Biomes 1.7.0 (ENABLED)
Border 1.0.7-SNAPSHOT-b24 (ENABLED)
Challenges 0.8.0 (ENABLED)
ExtraMobs 1.11.0.2 (ENABLED)
Level 1.9.3 (ENABLED)
imits 1.9.4 (ENABLED)
TwerkingForTrees 1.3.0 (ENABLED)
Warps 1.9.0 (ENABLED)
```

#### Plugins (Optional)

```
N/A
```
 
### Additional context (Optional)

N/A

**Comment by tastybento** [comment]
Please update. Fixed in https://github.com/BentoBoxWorld/AOneBlock/issues/21
