### ISSUE TITLE
Su yaratıklarının Doğması (AOneBlock Ocean Phase)

### ISSUE THREAD

**Issue by immakita** [BentoBoxWorld/AOneBlock#80]
### Description

Okyanus Biyomunda, Su yaratığı doğduğunda, Su çıkıyor. Bu çıkan su 2 blok genişliğinde 2 blok uzunluğunda, 2 Blok yüksekliğinde oluyor.

#### Steps to reproduce the behavior
 Yalnızca Okyanus Biyomuna geçip Su yaratıklarından birinin doğmasını bekleyebilirsiniz. Sorunu göreceksinizdir.

#### Expected behavior
Aslında hiç su çıkmaması gerekiyor (Benim düşüncem.) Yalnızca Yaratık veya hayvan doğmalı asla su olmamalı.

#### Screenshots and videos (Optional)
Örnek resim: https://cdn.discordapp.com/attachments/310623455462686720/716731918674034708/unknown.png

Minimum Olması gereken:
https://discordapp.com/channels/272499714048524288/310623455462686720/716733745788354562

##### BentoBox Version (Mandatory)
https://cdn.discordapp.com/attachments/702970124067667978/716909327503458334/unknown.png
_______

#### Plugins (Optional)
https://cdn.discordapp.com/attachments/702970124067667978/716909082296057866/unknown.png

_______
English translation:

Description

In the Ocean Biome, when the Creature of Water is born, Water comes out. This water is 2 blocks wide, 2 blocks long and 2 blocks high.

Steps to reproduce the behavior

You can simply switch to the Ocean Biome and wait for the birth of one of the Water creatures. You will see the problem.

Expected behavior

In fact, no water should come out (My opinion.) Only the Creature or the animal should be born and never be the water.

Screenshots and videos (Optional)

Example picture: https://cdn.discordapp.com/attachments/310623455462686720/716731918674034708/unknown.png

Must be a minimum:
https://discordapp.com/channels/272499714048524288/310623455462686720/716733745788354562

**Comment by immakita** [comment]
Edit:

Placeholder'lar OneBlock dünyası haricinde başka bir yerde iken çalışmıyor, gözükmüyor.

**Comment by tastybento** [comment]
You can change whether water animals will spawn with water in the config.yml file: https://github.com/BentoBoxWorld/AOneBlock/blob/develop/src/main/resources/config.yml#L242

**Comment by tastybento** [comment]
> Edit:
> 
> Placeholder'lar OneBlock dünyası haricinde başka bir yerde iken çalışmıyor, gözükmüyor.
> 
> Placeholders do not appear when they are in a place other than the OneBlock world.

Which placeholders?

**Comment by immakita** [comment]
{aoneblock_visited_island_count}

**Comment by immakita** [comment]
{aoneblock_visited_island_phase}

**Comment by tastybento** [comment]
Yes, these will not show up because they are from the island you are **visiting**. If you are not on an island, then they cannot show anything. You can only use these :

`%aoneblock_my_island_phase%` - the phase of your island
`%aoneblock_my_island_count%` - the block count of your island


Evet, bunlar görünmeyecek çünkü ziyaret ettiğiniz adadan geliyorlar. Eğer bir adada değilseniz, hiçbir şey gösteremezler. Yalnızca şunları kullanabilirsiniz:

`%aoneblock_my_island_phase%`
`%aoneblock_my_island_count%`
