### ISSUE TITLE
AOneBlock 1.3.0 Error

### ISSUE THREAD

**Issue by hvrry** [BentoBoxWorld/AOneBlock#82]
#### Describe the bug

Since updating to AOneBlock 1.3.0, there's an error in console

#### Steps to reproduce the behavior

Happens just as players are using the generator https://hastebin.com/qeyofixixe.sql
#### Expected behavior

No error?

#### Screenshots and videos (Optional)

https://hastebin.com/qeyofixixe.sql

##### BentoBox Version (Mandatory)

```
06.06 06:16:12 [Server] INFO Running PAPER 1.15.2
06.06 06:16:12 [Server] INFO BentoBox version: 1.13.1
06.06 06:16:12 [Server] INFO Database: MARIADB
06.06 06:16:12 [Server] INFO Loaded Game Worlds:
06.06 06:16:12 [Server] INFO oneblock_world (OneBlock): Overworld, Nether*
06.06 06:16:12 [Server] INFO Loaded Addons:
06.06 06:16:12 [Server] INFO AOneBlock 1.3.0 (ENABLED)
06.06 06:16:12 [Server] INFO Chat 1.0.5 (ENABLED)
06.06 06:16:12 [Server] INFO Likes 1.7.1 (ENABLED)
06.06 06:16:12 [Server] INFO Warps 1.9.5 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
Yes, this was fixed in 1.3.1 (https://github.com/BentoBoxWorld/AOneBlock/releases/tag/1.3.1)

BTW, thank you for being a sponsor!
