### ISSUE TITLE
Chests are completly empty #2 (Lang=tr Use Google Translate)

### ISSUE THREAD

**Issue by immakita** [BentoBoxWorld/AOneBlock#84]
#### Describe the bug

Daha önce size ilettiğimde dosyalarda hata görüp düzeltip Yeniden olmayacağını söyleyerek dosyaları bana atmıştınız. Tekrarladığı için biyomları tamamen kendim ayarladım. Sandıklar 60% oranda boş olarak spawnlanıyor.

When you sent it to you before, you threw the files at me by saying that there will be an error in the files and they will not be reinstalled. I set up the biomes completely myself for repeating. Chests are spawned 60% empty.

#### Steps to reproduce the behavior

Öncekinin aksine bütün biyomları silerek sandıkları da sıfırlayarak sandıkları komutla oluşturdum. Biyomlar Türkçe karakter içermektedir ama sorun yaratmıyorlar.

Unlike the previous one, by deleting all biomes, I reset the chests and created them with a command. Biomes contain Turkish characters but they don't cause any problems.
#### Expected behavior

Sandıklar boş çıkmamalı

Chests should not be empty
##### BentoBox Version (Mandatory)

```
https://imgur.com/53hnHNM
_______
```

#### Plugins (Optional)

```
__https://imgur.com/Sg1Zrfy_____
```
 
### Additional context (Optional)

[phases.zip](https://github.com/BentoBoxWorld/AOneBlock/files/4747812/phases.zip)

**Comment by tastybento** [comment]
If a chest type was picked that was not defined in the config, e.g., UNCOMMON, then the chest was set as empty. I have changed it to now pick the COMMON chest type. If COMMON is not defined, then the chest will be empty.

**Comment by immakita** [comment]
Ahhhhh okay, why you didn't tell me this information last 3 days :( I've closed my OneBlock server

**Comment by tastybento** [comment]
I work on this when I can because it's a hobby. It's now the weekend so I have a chance to look at it.

**Comment by immakita** [comment]
I just said it as a joke...
There is no problem
