### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ImFx-MC** [BentoBoxWorld/AOneBlock#86]
Hi, When I put BentoBox on my server with OneBlock addon, BlockBreakEvent does not work for me.

Here is error: https://hastebin.com/nobomidavo.pl

BentoBox and Server version output:
https://hastebin.com/manehuluci.css

Thanks for support.

**Comment by tastybento** [comment]
This is a duplicate of #85. Can you try the latest version of Paper Spigot and tell me if you still get the error: https://papermc.io/downloads ?

Where and when did you get your version of Spigot?

**Comment by tastybento** [comment]
Update your server and it will work.
