### ISSUE TITLE
Aoneblock doesnt work with jobs

### ISSUE THREAD

**Issue by kFxDaKing** [BentoBoxWorld/AOneBlock#88]
Hello, it seems Jobs doesnt work with aoneblock.
https://www.spigotmc.org/resources/jobs-reborn.4216/

Its possible to make it working somehow?

vid:
https://streamable.com/1brz4b

When you mine from generator, you dont get any moeny from job.

when you mine blocks that you placed, it works.

**Comment by maxlehot1234** [comment]
Same issue for me with this plugin:
https://www.spigotmc.org/resources/%E2%96%B6-quests-%E2%97%80-set-up-goals-for-players.23696/

@tastybento @Poslovitch ?
Is it something related to the way you handle block-break that prevent all other plugins to work with?

**Comment by tastybento** [comment]
Yes, probably. Right now the magic block is not compatible with these plugins. I currently do not know a way to make it compatible.

**Comment by maxlehot1234** [comment]
Maybe by setting BlockBreakEvent priority to something else like MONITOR? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maxlehot1234** [comment]
@tastybento 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tastybento** [comment]
@maxlehot1234 You don't need to tag me because I get notified of comments anyway.

Try the latest build and see if it helps. HIGHEST can be used, but MONITOR isn't supposed to be used because I change the event action. Anyway, let me know if this helps.

**Comment by maxlehot1234** [comment]
Don't seems to work. I Update aoneblock, bentobox, but still not able to got it count using my quest plugin (probably the same for @wolgix with Jobs Reborn
Maybe set it to LOW, LOWEST, NORMAL?
So your plugin will not had the "last word" ?

**Comment by BONNe** [comment]
Well, tasty, I think the issue could be with "physic" applying or speed at which blocks are replaced.
As after you added the same thing in MagicCobblestoneGenerator, it stopped detecting in McMMO.

**Comment by BONNe** [comment]
I found the issue with JOBS.
They use monitor that ignores cancelled tasks.
AOneBlock cancels BlockBeakEvent. 

**The current AOneBlock implementation is not compatible with JOBS.**

Jobs Code Reference: [JobsPaymentListener.java#L347](https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java#L347)

AOneBlock Reference: [BlockListener.java#L279](https://github.com/BentoBoxWorld/AOneBlock/blob/develop/src/main/java/world/bentobox/aoneblock/listeners/BlockListener.java#L279)

**Comment by tastybento** [comment]
I suspect this is true of McMMO and others too. Unfortunately, there doesn't seem to be a way to not-cancel this because if you don't then players can fall through the block if they are standing on it. I think I'm going to pass on this one for now and say that you need to break other blocks for jobs.

**Comment by maxlehot1234** [comment]
Kinda "stupid" since players can get stone only from magic block for example.
A lot of blocks can be break only from the magic-block.

I am pretty sure that you can fix it. 99.9999% sure in fact.

**Comment by wolgix** [comment]
yea jobs are kinda usseles now..

**Comment by maxlehot1234** [comment]
Yeah just like any quest plugin. Removing mining quests his so useless on this type of server.

**Comment by maxlehot1234** [comment]
In fact, another dev "fork" my quests plugin and make it work for other plugins and it work great with AOneBlock.

He change the blockbreakevent priority and it seems to work

**Comment by maxlehot1234** [comment]
Also, I know that version 4.0.4 of https://www.mc-market.org/resources/13696/ works perfectly with the AoneBlock infinite block, so there is a way for dev to make it work.

But I am pretty sure that bentobox devs can do something and simply prevent players to pass trough the block.

**Comment by tastybento** [comment]
I've implemented an option that _should_ work, but you guys need to test. The player will now not fall through the block. However, to use, set `drop-on-top` to `false` in config.yml: 
```
drop-on-top: false
```

Drop on top is not compatible with this because it has to cancel the break block event to work.

**Comment by kFxDaKing** [comment]
Hello just tested it with Jobs Reborn 4.16.3 and its not working.
I have miner job and im trying to mine from magic block, and its not counting.
drop-on-top: is on false
![image](https://user-images.githubusercontent.com/52855882/98472484-a9888c80-21f3-11eb-8cf4-277246120cbb.png)

**Comment by kFxDaKing** [comment]
JetsMinions | Upgrades | Customise Minion Skins | Actions | Animations | Robots | [1.8 - 1.16] 6.6.5
Dont work too, magic block disapear when miner mine that.

**Comment by tastybento** [comment]
I just tested with Jobs v4.16.3 and I picked the Woodcutter job and it works when I cut oak blocks with an axe.
I just tried as a miner and it works too:
<img width="851" alt="Screen Shot 2020-11-08 at 11 38 24 AM" src="https://user-images.githubusercontent.com/4407265/98482555-0ade3a80-21b7-11eb-9c33-43fdfc681e77.png">

If drop-on-top is definitely false, then AOneBlock is doing absolutely nothing when a block is mined, so this is why it works. Double check your settings.



> JetsMinions | Upgrades | Customise Minion Skins | Actions | Animations | Robots | [1.8 - 1.16] 6.6.5
> Dont work too, magic block disapear when miner mine that.

This is a different issue. Please make another issue for it. It may not be fixable unless these auto-actions are made by a fake player, in which case the player's name needs to be in the BentoBox config.yml fake player list.

**Comment by kFxDaKing** [comment]
Well, thats weird, since my versions are correct and settings too..
Thank ill try to look around what could cause it..

**Comment by kFxDaKing** [comment]
Hello, its still not working, it always work just for a while, then it stops work, and Jobs plugin stop counting broken blocks.

When i teleport to normal world here it works, but its not counting blocks from oneblock untill server restart, and then it works just for few minutes.

**Comment by tastybento** [comment]
Weird. Do you say it stops working after a few minutes? That makes me think it is more a bug with Jobs. With the above change, AOneBlock is doing nothing in regards to block-breaking other than generating the block again.

**Comment by kFxDaKing** [comment]
Yeah it works for few minutes after server restart, then it stops work.
When i tp to normal world it works ok.
