### ISSUE TITLE
Lag/Tick problem 15+ players

### ISSUE THREAD

**Issue by wolgix** [BentoBoxWorld/AOneBlock#89]
Hello i have problem with tick and lags when i reach more then 15 players.

https://timings.aikar.co/?id=9e19405786c047759fe24be92aac3614

Dedicated OVH server.
32GB DDR4 ECC 2666MHz
2x SSD NVMe 500GB Enterprise Class Soft RAID
1Gbps unmetered public bandwidth
Intel Xeon-E 2136 - 6c/ 12t - 3.3GHz/ 4.5GHz

**Comment by tastybento** [comment]
There doesn't seem to be anything specific that jumps out except for the "✗ Wrong Garbage Collector FIX THIS Switch Java flags to stop receiving lag spikes." error in the timings report. Try and run with Aikar's flags and see how that works for you.

**Comment by wolgix** [comment]
fixed, it wasnt asyblock problem.
