### ISSUE TITLE
[Feature] Implement a /ob visit <playername> command

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/AOneBlock#91]
Hi is it possible for you to implement this command: /ob visit playername

This will allow anyone to visit another player island.
Maybe put the visitor as a "ghost" (not spectator) so he will NOT push players, mobs, etc outside of the island.

#### Describe alternatives you've considered.

Giving /oba tp playername is not the best thing I think ;)

Thanks again

**Comment by Poslovitch** [comment]
Hi!
This feature is already suggested as an "Addon Request" on BentoBox's repository. See this: https://github.com/BentoBoxWorld/BentoBox/issues/841.

I'm closing this ticket, as it is a duplicate.

Thanks for your feature request ;)
