### ISSUE TITLE
Add new phases ?

### ISSUE THREAD

**Issue by victoryneM** [BentoBoxWorld/AOneBlock#93]
Hi, should it be possible to add new phases ? In order to make something new :)

**Comment by BONNe** [comment]
Well yes. You just need to follow the same approach as it is existing files.

**Comment by victoryneM** [comment]
OK, si just to add the config file with the name of new file ?

Victoryne

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BONNe** [comment]
So, the file must be in phases folder.

The file name must be in the format [blocks]_[name].yml and [blocks]_[name]_chests.yml where

- [blocks] is a number of blocks when phase will start to work
- [name] is phase name with all lowercase and white spaces are replaced with `_`. 
- only eng in a filename

[blocks]_[name].yml and [blocks]_[name]_chests.yml  :

- first-line should be `'[blocks]':` where blocks are replaced with the number of blocks. The same as in filename.
- You can check how it is in f.e. plains or plains chest, and you should follow the same approach.

**Comment by victoryneM** [comment]
thanks
