### ISSUE TITLE
A region for the block

### ISSUE THREAD

**Issue by victoryneM** [BentoBoxWorld/AOneBlock#94]
Hi,
I have a request, is it possible to add a region for the magicblock alone ? So that we can stop for example mob spawning except on the magic block. This shloud be an admin command to add flag on this specific region, which should not be submitted by the island rules.
Or other way, in ob settings, having a specific setting for mob spawning on the magic block, true false, so we can hide the setting or not. And this setting should be independant from the setting for ob concerning mob spawning.

**Comment by BONNe** [comment]
Island settings affect only natural mob spawning.
These options can be hidden from users, so they cannot change

**Comment by victoryneM** [comment]
well it seems to affect also the spawn mobs from the magic block...

victoryne

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by victoryneM** [comment]
Well ok, I mean the config where I can put the type of mobs I don't want to spawn on island, this affect also the mob sapwning of the magic block. I explain, I don't want zombie-villages on the island but only on the magic block, is  it possible ?

**Comment by tastybento** [comment]
This is no possible right now, sorry.
