### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by victoryneM** [BentoBoxWorld/AOneBlock#95]
When we make the command /ob phases we have the message 'An internal occurred while attempting to perform this command'. Could you help me ? The only thing made is modify the chest in two phases and mob spawning in two phases also.
I have also an error while attempting to add a chest in game, message is 'Look at a filled chest to set it' and I a m looking at a filled chest !
I guess I broke something Oo

**Comment by victoryneM** [comment]
Just in case, here is the error I have in console :

https://pastebin.com/2Pn11As3

**Comment by BONNe** [comment]
Your spigot / paper version is outdated.
Use newest one.
(to get newest spigot you need to build it using BuildTools)
